### ISSUE TITLE
last release runsc can't run

### ISSUE THREAD

**Issue by unknowndev233** [google/gvisor#6300] opened 2021-07-09 10:12 UTC
**Description**

After downloading the runsc according to the installation section in the gvisor.dev documentation, I found that it does not work

**Steps to reproduce**

1. run:
```
$ (
  set -e
  ARCH=$(uname -m)
  URL=https://storage.googleapis.com/gvisor/releases/release/latest/${ARCH}
  wget ${URL}/runsc ${URL}/runsc.sha512
  sha512sum -c runsc.sha512
  rm -f *.sha512
  chmod a+rx runsc
)
```

2. run `$ ./runsc --help`
Get error output:
```
SIGILL: illegal instruction
PC=0xe2fce4 m=0 sigcode=2
instruction bytes: 0xf 0x1 0xd0 0x89 0x44 0x24 0x10 0x89 0x54 0x24 0x14 0xc3 0xcc 0xcc 0xcc 0xcc

goroutine 1 [running, locked to thread]:
gvisor.dev/gvisor/pkg/ring0.xgetbv(0x0, 0xc00017e960)
        pkg/ring0/lib_amd64.s:171 +0x4 fp=0xc0001c1620 sp=0xc0001c1618 pc=0xe2fce4
gvisor.dev/gvisor/pkg/ring0.init()
        pkg/ring0/kernel_amd64.go:257 +0x62e fp=0xc0001c1658 sp=0xc0001c1620 pc=0xe2f16e
runtime.doInit(0x1bab740)
        GOROOT/src/runtime/proc.go:6265 +0xec fp=0xc0001c17a8 sp=0xc0001c1658 pc=0x4485ac
runtime.doInit(0x1bb1080)
        GOROOT/src/runtime/proc.go:6242 +0x72 fp=0xc0001c18f8 sp=0xc0001c17a8 pc=0x448532
runtime.doInit(0x1ba6260)
        GOROOT/src/runtime/proc.go:6242 +0x72 fp=0xc0001c1a48 sp=0xc0001c18f8 pc=0x448532
runtime.doInit(0x1bb82e0)
        GOROOT/src/runtime/proc.go:6242 +0x72 fp=0xc0001c1b98 sp=0xc0001c1a48 pc=0x448532
runtime.doInit(0x1bb2f00)
        GOROOT/src/runtime/proc.go:6242 +0x72 fp=0xc0001c1ce8 sp=0xc0001c1b98 pc=0x448532
runtime.doInit(0x1bae300)
        GOROOT/src/runtime/proc.go:6242 +0x72 fp=0xc0001c1e38 sp=0xc0001c1ce8 pc=0x448532
runtime.doInit(0x1ba5620)
        GOROOT/src/runtime/proc.go:6242 +0x72 fp=0xc0001c1f88 sp=0xc0001c1e38 pc=0x448532
runtime.main()
        GOROOT/src/runtime/proc.go:208 +0x205 fp=0xc0001c1fe0 sp=0xc0001c1f88 pc=0x43a865
runtime.goexit()
        src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0001c1fe8 sp=0xc0001c1fe0 pc=0x472821

rax    0xc00017e960
rbx    0xc000120d80
rcx    0x0
rdx    0x30
rdi    0xc000120df8
rsi    0xc00017e960
rbp    0xc0001c1648
rsp    0xc0001c1618
r8     0x80
r9     0x6
r10    0x6
r11    0xc000120d80
r12    0x6
r13    0xc0001fd048
r14    0x8
r15    0xc000120d80
rip    0xe2fce4
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0
```

**Environment**

Please include the following details of your environment:
*   `uname -a`:

`Linux arch 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000 x86_64 GNU/Linux`

**Comment by ianlewis** [comment] 2021-07-12 04:38
Hmm, It works ok for me. Can you provide the contents of `/proc/cpuinfo` ?

**Comment by ianlewis** [comment] 2021-07-12 23:52
This may be a duplicate of https://github.com/google/gvisor/issues/5738.

**Comment by unknowndev233** [comment] 2021-07-14 13:18
> Hmm, It works ok for me. Can you provide the contents of `/proc/cpuinfo` ?

```
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 4
model name      : AMD Phenom(tm) II X4 965 Processor
stepping        : 3
microcode       : 0x1000086
cpu MHz         : 3415.434
cache size      : 512 KB
physical id     : 0
siblings        : 3
core id         : 0
cpu cores       : 3
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid tsc_known_freq pni cx16 x2apic popcnt hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch vmmcall
bugs            : tlb_mmatch fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips        : 6833.48
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 4
model name      : AMD Phenom(tm) II X4 965 Processor
stepping        : 3
microcode       : 0x1000086
cpu MHz         : 3415.434
cache size      : 512 KB
physical id     : 0
siblings        : 3
core id         : 1
cpu cores       : 3
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid tsc_known_freq pni cx16 x2apic popcnt hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch vmmcall
bugs            : tlb_mmatch fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips        : 6833.48
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : AuthenticAMD
cpu family      : 16
model           : 4
model name      : AMD Phenom(tm) II X4 965 Processor
stepping        : 3
microcode       : 0x1000086
cpu MHz         : 3415.434
cache size      : 512 KB
physical id     : 0
siblings        : 3
core id         : 2
cpu cores       : 3
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid tsc_known_freq pni cx16 x2apic popcnt hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch vmmcall
bugs            : tlb_mmatch fxsave_leak sysret_ss_attrs null_seg amd_e400 spectre_v1 spectre_v2
bogomips        : 6833.48
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:
```

**Comment by prattmic** [comment] 2021-07-14 14:28
cc @avagin

**Closed** 2021-07-20 19:07 UTC
Labels: type: bug

**Comment by unknowndev233** [comment] 2021-07-21 05:04
today run `$ (
  set -e
  ARCH=$(uname -m)
  URL=https://storage.googleapis.com/gvisor/releases/release/latest/${ARCH}
  wget ${URL}/runsc ${URL}/runsc.sha512
  sha512sum -c runsc.sha512
  rm -f *.sha512
  chmod a+rx runsc
) && runsc --version`

output:
```
SIGILL: illegal instruction
PC=0xe2e024 m=0 sigcode=2
instruction bytes: 0xf 0x1 0xd0 0x89 0x44 0x24 0x10 0x89 0x54 0x24 0x14 0xc3 0xcc 0xcc 0xcc 0xcc

goroutine 1 [running, locked to thread]:
gvisor.dev/gvisor/pkg/ring0.xgetbv(0x0, 0xc0001a6960)
        pkg/ring0/lib_amd64.s:171 +0x4 fp=0xc0001e9620 sp=0xc0001e9618 pc=0xe2e024
gvisor.dev/gvisor/pkg/ring0.init()
        pkg/ring0/kernel_amd64.go:257 +0x62e fp=0xc0001e9658 sp=0xc0001e9620 pc=0xe2d4ae
runtime.doInit(0x1b9a620)
        GOROOT/src/runtime/proc.go:6265 +0xec fp=0xc0001e97a8 sp=0xc0001e9658 pc=0x4485ac
runtime.doInit(0x1ba0260)
        GOROOT/src/runtime/proc.go:6242 +0x72 fp=0xc0001e98f8 sp=0xc0001e97a8 pc=0x448532
runtime.doInit(0x1b95100)
        GOROOT/src/runtime/proc.go:6242 +0x72 fp=0xc0001e9a48 sp=0xc0001e98f8 pc=0x448532
runtime.doInit(0x1ba71e0)
        GOROOT/src/runtime/proc.go:6242 +0x72 fp=0xc0001e9b98 sp=0xc0001e9a48 pc=0x448532
runtime.doInit(0x1ba20e0)
        GOROOT/src/runtime/proc.go:6242 +0x72 fp=0xc0001e9ce8 sp=0xc0001e9b98 pc=0x448532
runtime.doInit(0x1b9d3c0)
        GOROOT/src/runtime/proc.go:6242 +0x72 fp=0xc0001e9e38 sp=0xc0001e9ce8 pc=0x448532
runtime.doInit(0x1b94500)
        GOROOT/src/runtime/proc.go:6242 +0x72 fp=0xc0001e9f88 sp=0xc0001e9e38 pc=0x448532
runtime.main()
        GOROOT/src/runtime/proc.go:208 +0x205 fp=0xc0001e9fe0 sp=0xc0001e9f88 pc=0x43a865
runtime.goexit()
        src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0001e9fe8 sp=0xc0001e9fe0 pc=0x472821

rax    0xc0001a6960
rbx    0xc00013b050
rcx    0x0
rdx    0x38
rdi    0xc00013b0d0
rsi    0xc0001a6960
rbp    0xc0001e9648
rsp    0xc0001e9618
r8     0x80
r9     0x7
r10    0x6
r11    0xc00013b050
r12    0x7
r13    0xc000266238
r14    0x8
r15    0xc00013b170
rip    0xe2e024
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by unknowndev233** [comment] 2021-07-21 05:04
cc @avagin

**Comment by avagin** [comment] 2021-07-21 05:19
0:  0f 01 d0                xgetbv

**Comment by unknowndev233** [comment] 2021-07-21 05:23
> 0: 0f 01 d0 xgetbv

What is that

**Comment by avagin** [comment] 2021-07-21 05:37
> > 0: 0f 01 d0 xgetbv

> What is that

This is the instruction that faulted.

$  wget https://storage.googleapis.com/gvisor/releases/release/latest/x86_64/runsc
$ chmod +x runsc
$ ./runsc --version
runsc version release-20210712.0
spec: 1.0.2

This is the latest stable release. You probably want to use a nightly build, but you need to wait for tomorrow to get a build with my fix.

$ https://storage.googleapis.com/gvisor/releases/nightly/latest/x86_64/runsc

**Comment by avagin** [comment] 2021-07-21 20:23
I have checked that [runsc](https://storage.googleapis.com/gvisor/releases/nightly/latest/x86_64/runsc) contains my fix. Could you try it out?

**Comment by unknowndev233** [comment] 2021-07-22 07:44
> I have checked that [runsc](https://storage.googleapis.com/gvisor/releases/nightly/latest/x86_64/runsc) contains my fix. Could you try it out?

fixed
