### ISSUE TITLE
lisafs not releasing disk space on deletion

### ISSUE THREAD

**Issue by fffe** [google/gvisor#7613] opened 2022-05-20 01:00 UTC
### Description

When using lisafs gvisor does not seem to release disk space when a file is deleted, until the container is destroyed.

I spun up a docker container under gvisor, with a volume mounted from the host system. I created a large file (~2.5GB) in the mount path, and then deleted it. When using `--lisafs`, running du on the directory shows that the directory is empty, but df on the mount point shows the space is still allocated. Without `--lisafs` the space is freed immediately.

```
root@744dfc318ae7:/download# df -h /download
Filesystem      Size  Used Avail Use% Mounted on
none            137G  2.5G  127G   2% /download
root@744dfc318ae7:/download# du -sh /download
20K     /download
```

The host system also shows 2.5G used on the mount point. That makes me think that the gofer still has some kind of reference to it.

### Steps to reproduce

I'm running a generic ubuntu container under gvisor in Docker. Docker's daemon.json looks like this:

```
{
    "live-restore": true,
    "runtimes": {
        "gvisor": {
            "path": "/usr/bin/runsc",
            "runtimeArgs": [
                "--platform=kvm",
                "--network=host",
                "--lisafs"
            ]
        }
}
```

Run a container with a mount point from the host system. Create a large file in the container (`dd if=/dev/zero of=/path/file bs=...`) and then rm it. With lisafs enabled, the file will be removed, but the space will not be freed. This can be seen by comparing du and df output for the mount point.

Destroy the container and verify that the space has now been freed using du/df on the host system.

### runsc version

```shell
runsc version release-20220510.0
spec: 1.0.2-dev
```

### docker version (if using docker)

```shell
Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:18:18 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:16:22 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### uname

Linux hostname 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ayushr2** [comment] 2022-05-20 20:07
Thank you @fffe for all the details and the reproducer.

I believe this is happening because LISAFS gofer client (in the sentry) does batch closing. When an FD is closed or a file is destroyed, lisafs client decides to batch [100 Close RPCs](https://cs.opensource.google/gvisor/gvisor/+/master:pkg/lisafs/client.go;l=30-34;drc=f6ed4523dceb2f90b4894b1f696a474da0a5341f) together. Close RPC is the most frequent RPC the sentry makes for various workloads as a lot of FDIDs are opened and closed. To minimize the roundtrip overhead of an RPC, lisafs decides to batch close 100 FDIDs at a time.

But you bring up a good point that this can lead to increase memory usage, like in the case you are showing. I am thinking of maybe implementing some sort of heuristic which disables batch closing for large files (hence making an immediate Close RPC). 1 MB can be an arbitrary limit of what classifies as a large file.

**Comment by fffe** [comment] 2022-05-20 20:25
> this can lead to increase memory usage, like in the case you are showing

I think it's disk space, not memory.

It would be nice if either the threshold or an on/off switch for batch closing were configurable. For this particular workload, effectively every operation is going to be over any threshold you're likely to pick.

It would also be nice if, when/before lisafs becomes the default, the batch closing was covered in the gvisor documentation, somewhere (well, somewhere more obvious than the API docs for the lisafs package). This is a fairly large operational change between lisafs and 9p.

Of course, I also realize this is currently gated by a feature flag and not ready yet. :)

Thanks!

**Comment by fvoznika** [comment] 2022-05-23 15:52
@ayushr2, lisafs should also release batched FDs on a timer to avoid holding files open indefinitely.

**Closed** 2022-05-24 23:11 UTC
Labels: type: bug

**Comment by ayushr2** [comment] 2022-05-24 23:29
> @ayushr2, lisafs should also release batched FDs on a timer to avoid holding files open indefinitely.

@fvoznika yeah I agree, we should eventually move to something like that. There might be some increased CPU overhead of maintaining another goroutine which checks the queue in intervals.
