### ISSUE TITLE
'unknown field Size in struct literal of type "golang.org/x/sys/unix".XDPUmemReg' with golang.org/x/sys v0.20.0

### ISSUE THREAD

**Issue by anthonyfok** [google/gvisor#10483] opened 2024-05-26 09:38 UTC
### Description

This is a "future" bug report for when you upgrade to golang.org/x/sys v0.20.0.

Debian unstable/sid has recently upgraded golang-golang-x-sys package to 0.20.0-1, and a test rebuild of golang-gvisor-gvisor with the new golang-golang-x-sys-dev/0.20.0-1 failed on Debian CI:

![image](https://github.com/google/gvisor/assets/1274764/7a6f3f84-1551-4591-838c-a31edb12261b)
(from <https://ci.debian.net/packages/g/golang-gvisor-gvisor/testing/amd64/>)

with the following build error:
```
# gvisor.dev/gvisor/pkg/xdp
src/gvisor.dev/gvisor/pkg/xdp/xdp.go:156:3: unknown field Size in struct literal of type "golang.org/x/sys/unix".XDPUmemReg
```
See https://ci.debian.net/packages/g/golang-gvisor-gvisor/testing/amd64/47000334/#L1732 for the full log.

It turns out that, in commit golang/sys@27dc90bcf4d797251506d82bd56307ca2c13d59c leading up to golang.org/x/sys v0.20.0:

```
commit 27dc90bcf4d797251506d82bd56307ca2c13d59c
Author: Tobias Klauser <tklauser@distanz.ch>
Date:   Wed Apr 10 19:12:34 2024 +0200

    unix: update to Linux kernel 6.4
    
    Change-Id: I88b628a97f5cfb76083968be2ff2e9857ce56557
    Reviewed-on: https://go-review.googlesource.com/c/sys/+/577975
    Auto-Submit: Tobias Klauser <tobias.klauser@gmail.com>
    LUCI-TryBot-Result: Go LUCI <golang-scoped@luci-project-accounts.iam.gserviceaccount.com>
    Reviewed-by: Ian Lance Taylor <iant@google.com>
    Reviewed-by: Carlos Amedee <carlos@golang.org>
```

```go
type XDPUmemReg struct {
	Addr     uint64
	Len      uint64
	Size     uint32
	Headroom uint32
	Flags    uint32
	_        [4]byte
}
```

was changed to this:

```go
type XDPUmemReg struct {
	Addr            uint64
	Len             uint64
	Chunk_size      uint32
	Headroom        uint32
	Flags           uint32
	Tx_metadata_len uint32
}
```

where Size was renamed to Chunk_size.  See https://go-review.googlesource.com/c/sys/+/577975.

Here is the quick fix that I am using to get golang-gvisor-gvisor to build with golang-golang-x-sys-dev 0.20.0-1:

```diff
--- a/pkg/xdp/xdp.go
+++ b/pkg/xdp/xdp.go
@@ -151,9 +151,9 @@
 	}
 
 	reg := unix.XDPUmemReg{
-		Addr: uint64(sliceBackingPointer(umemMemory)),
-		Len:  uint64(len(umemMemory)),
-		Size: opts.FrameSize,
+		Addr:       uint64(sliceBackingPointer(umemMemory)),
+		Len:        uint64(len(umemMemory)),
+		Chunk_size: opts.FrameSize,
 		// Not useful in the RX path.
 		Headroom: 0,
 		// TODO(b/240191988): Investigate use of SHARED flag.
```

I wonder if FrameSize should be renamed to ChunkSize too, but I don't know AF_XDP well enough to know the answer.

Thanks!

### Steps to reproduce

```
$ git clone https://github.com/google/gvisor.git
Cloning into 'gvisor'...
remote: Enumerating objects: 185071, done.
remote: Counting objects: 100% (1506/1506), done.
remote: Compressing objects: 100% (769/769), done.
remote: Total 185071 (delta 845), reused 1234 (delta 716), pack-reused 183565
Receiving objects: 100% (185071/185071), 84.75 MiB | 11.10 MiB/s, done.
Resolving deltas: 100% (133924/133924), done.

$ cd gvisor

$ go get golang.org/x/sys
go: upgraded golang.org/x/sys v0.17.0 => v0.20.0

$ go build gvisor.dev/gvisor/pkg/xdp
# gvisor.dev/gvisor/pkg/xdp
pkg/xdp/xdp.go:158:3: unknown field Size in struct literal of type "golang.org/x/sys/unix".XDPUmemReg
```

### repo state (if built from source)

release-20240520.0-15-ga244eff8a

**Comment by ayushr2** [comment] 2024-05-27 16:20
Thanks for the heads up. We will fix this when we upgrade to golang.org/x/sys v0.20.0. We have a lot of tests in place to catch such build failures when the upgrade happens. Closing this for now as this is not a bug.

**Closed by ayushr2** 2024-05-27 16:20 UTC
Labels: type: bug
