### ISSUE TITLE
mkfifo Operation not permitted in /tmp with volumes mounted as sub-directories of /tmp

### ISSUE THREAD

**Issue by TrevorSundberg** [google/gvisor#1681] opened 2020-01-27 19:38 UTC
### Issue
Cannot create fifo using `mkfifo` in `/tmp/` when a volume is mounted as a sub-directory, such as `/tmp/123`. This works if I use `--runtime runc` but not with `--runtime runsc`.

### Minimum Repro
```dockerfile
FROM alpine
CMD mkfifo /tmp/test
```

```
docker build -t fifotmp .
docker run --rm -v /tmp/123:/tmp/123 --runtime runsc fifotmp
```

```
Step 1/2 : FROM alpine
 ---> 961769676411
Step 2/2 : CMD mkfifo /tmp/test
 ---> Using cache
 ---> b80bf3304dd0
Successfully built b80bf3304dd0
Successfully tagged fifotmp:latest
mkfifo: /tmp/test: Operation not permitted
```

Other operations such as `touch /tmp/test` succeed.
May be related to: https://github.com/google/gvisor/issues/1102

If I understand correctly, if there are any files within `/tmp/` then the internal tmpfs is not mounted, which I suspect is related to this issue.
https://github.com/google/gvisor/blob/ea7a100202f01601fba613a76f106a9a45c817c8/runsc/boot/fs.go#L970
https://github.com/google/gvisor/blob/ea7a100202f01601fba613a76f106a9a45c817c8/runsc/boot/fs.go#L995

### System Info
```
$ runsc --version
runsc version release-20191213.0
spec: 1.0.1-dev
```
```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.3
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        a872fc2f86
 Built:             Tue Oct  8 00:59:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       a872fc2f86
  Built:            Tue Oct  8 00:58:31 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1335
 Server Version: 19.03.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runsc runsc-custom runsc-debug runsc-kvm runsc-profile runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.0-26-generic
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 31.29GiB
 Name: tsundberg-dev
 ID: NEKK:WXAP:7PLW:OIP5:VSWC:ZUYP:4SPU:VSWM:I2PO:3PWL:CK65:FTFH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
```
$ uname -a
Linux tsundberg-dev 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### Logs
```
boot:
I0127 19:25:48.787668  124813 x:0] Skipping internal tmpfs on top "/tmp", because it's not empty
...
I0127 19:05:58.168756  120824 x:0] [   1] sh E stat(0x558854fb8cb0 /usr/local/sbin/mkfifo, 0x7f3f087f9918)
D0127 19:05:58.168841  120824 x:0] send [channel @0xc00020c900] Twalkgetattr{FID: 1, NewFID: 20, Names: [usr]}
D0127 19:05:58.169348  120824 x:0] recv [channel @0xc00020c900] Rwalkgetattr{Valid: AttrMask{with: Mode NLink UID GID RDev ATime MTime CTime Size Blocks}, Attr: Attr{Mode: 0o40755, UID: 0, GID: 0, NLink: 7, RDev: 0, Size: 4096, BlockSize: 4096, Blocks: 8, ATime: {Sec: 1573605799, NanoSec: 537955477}, MTime: {Sec: 1566297043, NanoSec: 0}, CTime: {Sec: 1569347521, NanoSec: 685047351}, BTime: {Sec: 0, NanoSec: 0}, Gen: 0, DataVersion: 0}, QIDs: [QID{Type: 128, Version: 0, Path: 17564120}]}
D0127 19:05:58.169428  120824 x:0] send [channel @0xc00020c900] Twalkgetattr{FID: 20, NewFID: 21, Names: [local]}
D0127 19:05:58.169682  120824 x:0] recv [channel @0xc00020c900] Rwalkgetattr{Valid: AttrMask{with: Mode NLink UID GID RDev ATime MTime CTime Size Blocks}, Attr: Attr{Mode: 0o40755, UID: 0, GID: 0, NLink: 5, RDev: 0, Size: 4096, BlockSize: 4096, Blocks: 8, ATime: {Sec: 1573605799, NanoSec: 537955477}, MTime: {Sec: 1566297043, NanoSec: 0}, CTime: {Sec: 1569347521, NanoSec: 685047351}, BTime: {Sec: 0, NanoSec: 0}, Gen: 0, DataVersion: 0}, QIDs: [QID{Type: 128, Version: 0, Path: 17564274}]}
D0127 19:05:58.169926  120824 x:0] send [channel @0xc00020c900] Twalkgetattr{FID: 21, NewFID: 22, Names: [sbin]}
D0127 19:05:58.169988  120824 x:0] recv [channel @0xc00020c900] Rlerror{Error: 2}
I0127 19:05:58.170015  120824 x:0] [   1] sh X stat(0x558854fb8cb0 /usr/local/sbin/mkfifo, 0x7f3f087f9918) = 0x0 errno=2 (no such file or directory) (1.24333ms)
I0127 19:05:58.170271  120824 x:0] [   1] sh E stat(0x558854fb8cb0 /usr/local/bin/mkfifo, 0x7f3f087f9918)
D0127 19:05:58.170298  120824 x:0] send [channel @0xc00020c900] Twalkgetattr{FID: 21, NewFID: 22, Names: [bin]}
D0127 19:05:58.170396  120824 x:0] recv [channel @0xc00020c900] Rwalkgetattr{Valid: AttrMask{with: Mode NLink UID GID RDev ATime MTime CTime Size Blocks}, Attr: Attr{Mode: 0o40755, UID: 0, GID: 0, NLink: 2, RDev: 0, Size: 4096, BlockSize: 4096, Blocks: 8, ATime: {Sec: 1573605799, NanoSec: 541955540}, MTime: {Sec: 1566297043, NanoSec: 0}, CTime: {Sec: 1569347521, NanoSec: 685047351}, BTime: {Sec: 0, NanoSec: 0}, Gen: 0, DataVersion: 0}, QIDs: [QID{Type: 128, Version: 0, Path: 17564275}]}
D0127 19:05:58.170445  120824 x:0] send [channel @0xc00020c900] Twalkgetattr{FID: 22, NewFID: 23, Names: [mkfifo]}
D0127 19:05:58.170491  120824 x:0] recv [channel @0xc00020c900] Rlerror{Error: 2}
I0127 19:05:58.170506  120824 x:0] [   1] sh X stat(0x558854fb8cb0 /usr/local/bin/mkfifo, 0x7f3f087f9918) = 0x0 errno=2 (no such file or directory) (217.792µs)
I0127 19:05:58.170561  120824 x:0] [   1] sh E stat(0x558854fb8cb0 /usr/sbin/mkfifo, 0x7f3f087f9918)
D0127 19:05:58.170595  120824 x:0] send [channel @0xc00020c900] Twalkgetattr{FID: 20, NewFID: 23, Names: [sbin]}
D0127 19:05:58.170711  120824 x:0] recv [channel @0xc00020c900] Rwalkgetattr{Valid: AttrMask{with: Mode NLink UID GID RDev ATime MTime CTime Size Blocks}, Attr: Attr{Mode: 0o40755, UID: 0, GID: 0, NLink: 2, RDev: 0, Size: 4096, BlockSize: 4096, Blocks: 8, ATime: {Sec: 1573605799, NanoSec: 553955726}, MTime: {Sec: 1566297043, NanoSec: 0}, CTime: {Sec: 1569347521, NanoSec: 685047351}, BTime: {Sec: 0, NanoSec: 0}, Gen: 0, DataVersion: 0}, QIDs: [QID{Type: 128, Version: 0, Path: 17564278}]}
D0127 19:05:58.170735  120824 x:0] send [channel @0xc00020c900] Twalkgetattr{FID: 23, NewFID: 24, Names: [mkfifo]}
D0127 19:05:58.170806  120824 x:0] recv [channel @0xc00020c900] Rlerror{Error: 2}
I0127 19:05:58.170822  120824 x:0] [   1] sh X stat(0x558854fb8cb0 /usr/sbin/mkfifo, 0x7f3f087f9918) = 0x0 errno=2 (no such file or directory) (234.483µs)
I0127 19:05:58.170878  120824 x:0] [   1] sh E stat(0x558854fb8cb0 /usr/bin/mkfifo, 0x7f3f087f9918)
D0127 19:05:58.170902  120824 x:0] send [channel @0xc00020c900] Twalkgetattr{FID: 20, NewFID: 24, Names: [bin]}
D0127 19:05:58.170992  120824 x:0] recv [channel @0xc00020c900] Rwalkgetattr{Valid: AttrMask{with: Mode NLink UID GID RDev ATime MTime CTime Size Blocks}, Attr: Attr{Mode: 0o40755, UID: 0, GID: 0, NLink: 2, RDev: 0, Size: 4096, BlockSize: 4096, Blocks: 8, ATime: {Sec: 1573605799, NanoSec: 553955726}, MTime: {Sec: 1566297043, NanoSec: 0}, CTime: {Sec: 1569347521, NanoSec: 685047351}, BTime: {Sec: 0, NanoSec: 0}, Gen: 0, DataVersion: 0}, QIDs: [QID{Type: 128, Version: 0, Path: 17564121}]}
D0127 19:05:58.171022  120824 x:0] send [channel @0xc00020c900] Twalkgetattr{FID: 24, NewFID: 25, Names: [mkfifo]}
D0127 19:05:58.171115  120824 x:0] recv [channel @0xc00020c900] Rwalkgetattr{Valid: AttrMask{with: Mode NLink UID GID RDev ATime MTime CTime Size Blocks}, Attr: Attr{Mode: 0o120777, UID: 0, GID: 0, NLink: 1, RDev: 0, Size: 12, BlockSize: 4096, Blocks: 0, ATime: {Sec: 1566297043, NanoSec: 0}, MTime: {Sec: 1566297043, NanoSec: 0}, CTime: {Sec: 1569347521, NanoSec: 673047459}, BTime: {Sec: 0, NanoSec: 0}, Gen: 0, DataVersion: 0}, QIDs: [QID{Type: 2, Version: 0, Path: 17564184}]}
D0127 19:05:58.171136  120824 x:0] send [channel @0xc00020c900] Treadlink{FID: 25}
D0127 19:05:58.171177  120824 x:0] recv [channel @0xc00020c900] Rreadlink{Target: /bin/busybox}
I0127 19:05:58.171227  120824 x:0] [   1] sh X stat(0x558854fb8cb0 /usr/bin/mkfifo, 0x7f3f087f9918 {dev=16, ino=18, mode=S_IFREG|0o755, nlink=1, uid=0, gid=0, rdev=0, size=833104, blksize=4096, blocks=1627, atime=2020-01-27 19:05:58.16331862 +0000 UTC, mtime=2019-06-12 17:52:45 +0000 UTC, ctime=2019-09-24 17:52:01.629047854 +0000 UTC}) = 0x0 (300.748µs)
I0127 19:05:58.171319  120824 x:0] [   1] sh E execve(0x558854fb8ce0 /usr/bin/mkfifo, 0x558854fb8c98 ["mkfifo", "/tmp/test"], 0x558854fb8cb0 ["HOSTNAME=fa48e00d70d8", "SHLVL=1", "HOME=/root", "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "PWD=/"])
D0127 19:05:58.171348  120824 x:0] send [channel @0xc00020c900] Treadlink{FID: 25}
D0127 19:05:58.171385  120824 x:0] recv [channel @0xc00020c900] Rreadlink{Target: /bin/busybox}
D0127 19:05:58.171928  120824 x:0] [   1] Allocating stack with size of 8388608 bytes
I0127 19:05:58.172017  120824 x:0] [   1] sh X execve(0x558854fb8ce0 /usr/bin/mkfifo, 0x558854fb8c98 ["mkfifo", "/tmp/test"], 0x558854fb8cb0 ["HOSTNAME=fa48e00d70d8", "SHLVL=1", "HOME=/root", "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin", "PWD=/"]) = 0x0 (685.926µs)
I0127 19:05:58.173491  120824 x:0] [   1] mkfifo E arch_prctl(0x1002, 0x7f2f95198d48)
I0127 19:05:58.173514  120824 x:0] [   1] mkfifo X arch_prctl(0x1002, 0x7f2f95198d48) = 0x0 (1.864µs)
I0127 19:05:58.173541  120824 x:0] [   1] mkfifo E set_tid_address(0x7f2f9519931c)
I0127 19:05:58.173558  120824 x:0] [   1] mkfifo X set_tid_address(0x7f2f9519931c) = 0x1 (1.533µs)
I0127 19:05:58.173831  120824 x:0] [   1] mkfifo E mprotect(0x7f2f95195000, 0x1000, 0x1)
I0127 19:05:58.173892  120824 x:0] [   1] mkfifo X mprotect(0x7f2f95195000, 0x1000, 0x1) = 0x0 (47.469µs)
I0127 19:05:58.174091  120824 x:0] [   1] mkfifo E mprotect(0x5590e7208000, 0x4000, 0x1)
I0127 19:05:58.174151  120824 x:0] [   1] mkfifo X mprotect(0x5590e7208000, 0x4000, 0x1) = 0x0 (44.654µs)
I0127 19:05:58.174441  120824 x:0] [   1] mkfifo E getuid()
I0127 19:05:58.174459  120824 x:0] [   1] mkfifo X getuid() = 0x0 (2.003µs)
I0127 19:05:58.174602  120824 x:0] [   1] mkfifo E mknod(0x7f9da9460f65 /tmp/test, S_IFIFO|0o666, 0x0)
D0127 19:05:58.174653  120824 x:0] send [channel @0xc00020c900] Tumknod{Tmknod: Tmknod{DirectoryFID: 5, Name: test, Mode: 0o10644, Major: 0, Minor: 0, GID: 0}, UID: 0}
D0127 19:05:58.174771  120824 x:0] recv [channel @0xc00020c900] Rlerror{Error: 1}
I0127 19:05:58.174784  120824 x:0] [   1] mkfifo X mknod(0x7f9da9460f65 /tmp/test, S_IFIFO|0o666, 0x0) = 0x0 errno=1 (operation not permitted) (167.145µs)
I0127 19:05:58.174856  120824 x:0] [   1] mkfifo E write(0x2 host:[3], 0x7f9da9460bb8 "mkfifo: /tmp/test: Operation not permitted\n", 0x2b)
I0127 19:05:58.174886  120824 x:0] [   1] mkfifo X write(0x2 host:[3], ..., 0x2b) = 0x2b (17.713µs)
I0127 19:05:58.174930  120824 x:0] [   1] mkfifo E exit_group(0x1)
I0127 19:05:58.174941  120824 x:0] [   1] mkfifo X exit_group(0x1) = 0x0 (1.242µs)
D0127 19:05:58.174945  120824 x:0] [   1] Transitioning from exit state TaskExitNone to TaskExitInitiated
```

```
gopher:
D0127 19:05:58.171054       1 x:0] Attempt 0 to open file failed, mode: 0xa0800, path: "/usr/bin/mkfifo", err: too many levels of symbolic links
```

**Comment by fvoznika** [comment] 2020-01-27 21:54
You're exactly correct. When `/tmp` is empty, it's mounted as a sandbox-internal tmpfs mount to speed up `/tmp` access. The internal tmpfs implementation supports `mknod`, while the a p9 implementation doesn't. So when `/tmp` is not empty, it must be mounted as a regular p9 mount and `mkfifo` fails.

Can you please check if #1135 fixes the issue for you?

**Comment by TrevorSundberg** [comment] 2020-01-27 22:24
Indeed https://github.com/google/gvisor/pull/1135 does fix it :)

**Comment by fvoznika** [comment] 2020-02-04 16:23
Duplicate of #1102

**Closed by fvoznika** 2020-02-04 16:23 UTC
Labels: area: filesystem, priority: p1, type: bug
