### ISSUE TITLE
Error when running on Ubuntu 20.04

### ISSUE THREAD

**Issue by j75** [google/gvisor#5964] opened 2021-05-10 20:05 UTC
I am trying to reproduce the test shown at https://gvisor.dev/docs/user_guide/quick_start/docker/

```
$ docker run --runtime=runsc --rm hello-world
docker: Error response from daemon: OCI runtime create failed: creating container: starting sandbox: fork/exec /proc/self/exe: no space left on device: unknown.
```
The message may also be found in system log.
Without the ` --runtime=runsc` option I have
```
$ docker run --rm hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.
...
```

**Environment**

Please include the following details of your environment:

*   `runsc -version`
```
runsc version release-20210503.0
spec: 1.0.2
```
*   `docker version` 
```
Client:
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.2-0ubuntu1~20.04.2
 Built:             Tue Mar 30 21:24:57 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       20.10.2-0ubuntu1~20.04.2
  Built:            Mon Mar 29 19:10:09 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2.3
  GitCommit:        
 runc:
  Version:          spec: 1.0.2-dev
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
```
* or `docker info`
```
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 24
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc runsc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-50-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 11.56GiB
 Name: hp-pamela
 ID: TVOI:NAT2:YI76:GO3O:GC3G:X5ZS:DJEJ:Y7QL:G37D:RRUE:KLKX:32B3
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: xxx
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
...
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support
```
*  not using Kubernetes
*   `uname -a`
```
Linux hp-pamela 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ianlewis** [comment] 2021-05-16 22:50
@j75 Hi, can you add debugging flags to the `runsc`- runtime in `/etc/docker/daemon.json` and attach the logs? You can follow the steps here to add the right flags.
https://gvisor.dev/docs/user_guide/debugging/

**Comment by j75** [comment] 2021-05-17 21:35
In **/tmp** _runsc.log.20210517-232740.856549.gofer_ and _runsc.log.20210517-232740.860425.boot_ have 0 bytes, so I only add the _[runsc.log.20210517-232740.837173.create](https://github.com/google/gvisor/files/6496972/runsc.log.20210517-232740.837173.txt)_ file (with extension renamed to be able to upload it).

**Comment by fvoznika** [comment] 2021-05-20 23:47
The log looks fine, except for the error to fork/exec another process. `ENOSPC` can happen when the limit of user namespaces has been reached. In the logs, I can see that the gofer process was created just fine and it joins the existing user namespace. The sandbox in the other hand does create a new user namespace. docker also doesn't create user namespaces. It's a long short but check if you can create a new user namespace:

```
unshare --user
```

If that works, here a few more commands to try. These skip namespaces, chroot, etc and may help narrow where the problem is:

```
mkdir -a /tmp/runsc
sudo runsc --debug --debug-log=/tmp/runsc/ do echo 123
sudo runsc --debug --debug-log=/tmp/runsc/ --TESTONLY-unsafe-nonroot do echo 123
runsc --debug --debug-log=/tmp/runsc/ --rootless --network=none do echo 123
```

**Comment by ianlewis** [comment] 2021-05-21 00:03
Give a check at what `/proc/sys/user/max_user_namespaces` is set at. You may be running up against this limit. On some systems it's set a bit low.

**Comment by j75** [comment] 2021-05-22 15:40
Yes, that was the problem!
```
% cat /proc/sys/user/max_user_namespaces
0
```
Supplying an integer value (3) made everything working normally. What value would you suggest?

**Comment by ianlewis** [comment] 2021-05-24 01:52
RHEL 7 release notes recommend a high value like 15000
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.4_release_notes/new_features_kernel

**Comment by ianlewis** [comment] 2021-05-24 01:53
Sounds like this issue is resolved so I'm going to go ahead and close this.

**Closed by ianlewis** 2021-05-24 01:53 UTC
Labels: runtime: docker, type: bug

**Comment by zpavlinovic** [comment] 2024-08-05 14:06
I understand this issue is closed, but I was hoping I might some pointers. We've been seeing the below error message quite frequently lately

```
running container: creating container: cannot create gofer process: gofer: fork/exec /proc/self/exe: read-only file system: check whether /proc/sys/user/max_user_namespaces is set too low (gvisor.dev/issue/5964):
```

We are running gvisor iniside a docker container (that is ran on Google Cloud Run). Doing `cat /proc/sys/user/max_user_namespaces`  inside the container gives a large number > 0. `/proc/sys/user` does not seem to exist inside the gvisor sandbox.

We invoke the sandbox with `runsc  -ignore-cgroups -network=none -platform=systrap -dcache=500 ...`

Any idea why we might be seeing this error?

**Comment by ayushr2** [comment] 2024-08-05 16:33
cc @avagin (since this is gVisor-in-Docker)

**Comment by EtiennePerot** [comment] 2024-08-05 19:22
This "check whether /proc/sys/user/max_user_namespaces is set too low" hint is mentioned over-eagerly IMO. It is likely not the error. The "read-only file system" part of your error message sounds a lot more relevant. Please file a new bug and include all the details the bug template asks for (logs etc).
