### ISSUE TITLE
checklocks panic: `panic: interface conversion: interface is nil, not ssa.Value`

### ISSUE THREAD

**Issue by howardjohn** [google/gvisor#7721] opened 2022-06-13 22:47 UTC
### Description

```
panic: interface conversion: interface is nil, not ssa.Value

goroutine 33 [running]:
gvisor.dev/gvisor/tools/checklocks.(*globalGuard).resolveCommon(...)
        /usr/local/google/home/howardjohn/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220613221214-f3b72fa3ca19/tools/checklocks/facts.go:182
gvisor.dev/gvisor/tools/checklocks.(*globalGuard).resolveField(0xc0027a3110, 0xc000681810?, 0x7da080?, {0xc00817f860?, 0x12?})
        /usr/local/google/home/howardjohn/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220613221214-f3b72fa3ca19/tools/checklocks/facts.go:198 +0xa5
gvisor.dev/gvisor/tools/checklocks.(*passContext).checkGuards(0xc00801fc20, {0x7db5f0, 0xc003df9240}, {0x7dd730, 0xc003df9240}, {0x7de9a8?, 0xc000681810}, 0xc00828c780, 0x0)
        /usr/local/google/home/howardjohn/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220613221214-f3b72fa3ca19/tools/checklocks/analysis.go:218 +0x1e3
gvisor.dev/gvisor/tools/checklocks.(*passContext).checkGlobalAccess(...)
        /usr/local/google/home/howardjohn/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220613221214-f3b72fa3ca19/tools/checklocks/analysis.go:327
gvisor.dev/gvisor/tools/checklocks.(*passContext).checkInstruction(0x70ca80?, {0x7de150, 0xc0078c2780?}, 0xc008210d50, 0xc00828c780)
        /usr/local/google/home/howardjohn/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220613221214-f3b72fa3ca19/tools/checklocks/analysis.go:595 +0x114
gvisor.dev/gvisor/tools/checklocks.(*passContext).checkBasicBlock(0xc00801fc20, 0xc003aacdc0, 0xc0078a5080, 0xc008210d50, 0xc00828c740, 0x20?, 0x0)
        /usr/local/google/home/howardjohn/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220613221214-f3b72fa3ca19/tools/checklocks/analysis.go:708 +0x72f
gvisor.dev/gvisor/tools/checklocks.(*passContext).checkFunction(0xc00801fc20, {0x0, 0x0}, 0xc003aacdc0, 0xc008210d50, 0x0, 0x0)
        /usr/local/google/home/howardjohn/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220613221214-f3b72fa3ca19/tools/checklocks/analysis.go:808 +0x750
gvisor.dev/gvisor/tools/checklocks.run(0xc006ab1a00)
        /usr/local/google/home/howardjohn/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220613221214-f3b72fa3ca19/tools/checklocks/checklocks.go:177 +0x2d9
golang.org/x/tools/go/analysis/unitchecker.run.func5.1()
        /usr/local/google/home/howardjohn/go/pkg/mod/golang.org/x/tools@v0.1.9/go/analysis/unitchecker/unitchecker.go:355 +0x82e
sync.(*Once).doSlow(0x6e6f632d6f672f79?, 0x616c702d6c6f7274?)
        /usr/local/google/home/howardjohn/sdk/go1.18/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
        /usr/local/google/home/howardjohn/sdk/go1.18/src/sync/once.go:59
golang.org/x/tools/go/analysis/unitchecker.run.func5(0x98e9a0?)
        /usr/local/google/home/howardjohn/go/pkg/mod/golang.org/x/tools@v0.1.9/go/analysis/unitchecker/unitchecker.go:307 +0x1a5
golang.org/x/tools/go/analysis/unitchecker.run.func6.1(0x7061742f6e6f6d6d?)
        /usr/local/google/home/howardjohn/go/pkg/mod/golang.org/x/tools@v0.1.9/go/analysis/unitchecker/unitchecker.go:367 +0x29
created by golang.org/x/tools/go/analysis/unitchecker.run.func6
        /usr/local/google/home/howardjohn/go/pkg/mod/golang.org/x/tools@v0.1.9/go/analysis/unitchecker/unitchecker.go:366 +0x47
```

When running `checklocks ./pilot/...` against https://github.com/istio/istio branch. Go version is 1.18, installed by `go install gvisor.dev/gvisor/tools/checklocks/cmd/checklocks@go`.

I know checklocks is not quite a general purpose tool, but it seemed great so I was checking it out and ran into this. Some packages work, but some panic with this error.

### Steps to reproduce

Checkout https://github.com/istio/istio, run `checklocks ./pilot/...`

**Comment by amscanne** [comment] 2022-06-14 17:17
Whoops, looks like a validation missing for an invalid global guard. I'm actually not sure how it hits this, given that a global guard should not be constructed unless the symbol exists. I'll post a trivial fix for that issue, but to debug further, can you indicate the annotations that you tried?

**Comment by amscanne** [comment] 2022-06-14 19:04
Out of interest, I ran the analysis from the latest commit (w/ Go 1.19) but the problem didn't reproduce. So I think I'm missing an annotation.

FWIW, these were the results:

```
# istio.io/istio/pilot/cmd/pilot-agent/status/grpcready
pilot/cmd/pilot-agent/status/grpcready/probe.go:31:2: may require checklocks annotation for RWMutex, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/util/informermetric
pilot/pkg/util/informermetric/informerutil.go:36:2: may require checklocks annotation for mu, used with lock held 100% of the time
pilot/pkg/util/informermetric/informerutil.go:28:2: may require checklocks annotation for mu, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/serviceregistry/memory
pilot/pkg/serviceregistry/memory/discovery.go:31:2: may require checklocks annotation for RWMutex, used with lock held 100% of the time
pilot/pkg/serviceregistry/memory/discovery.go:67:2: may require checklocks annotation for mutex, used with lock held 100% of the time
pilot/pkg/serviceregistry/memory/discovery.go:56:2: may require checklocks annotation for mutex, used with lock held 100% of the time
pilot/pkg/serviceregistry/memory/discovery.go:69:2: may require checklocks annotation for mutex, used with lock held 100% of the time
pilot/pkg/serviceregistry/memory/discovery.go:68:2: may require checklocks annotation for mutex, used with lock held 100% of the time
pilot/pkg/serviceregistry/memory/discovery.go:63:2: may require checklocks annotation for mutex, used with lock held 100% of the time
pilot/pkg/serviceregistry/memory/discovery.go:62:2: may require checklocks annotation for mutex, used with lock held 100% of the time
# istio.io/istio/pilot/cmd/pilot-agent/status
pilot/cmd/pilot-agent/status/server.go:139:2: may require checklocks annotation for mutex, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/autoregistration
pilot/pkg/autoregistration/controller.go:140:2: may require checklocks annotation for mutex, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/serviceregistry/kube/controller/filter
pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go:51:2: may require checklocks annotation for lock, used with lock held 100% of the time
pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go:50:2: may require checklocks annotation for lock, used with lock held 100% of the time
pilot/pkg/serviceregistry/kube/controller/filter/discoverynamespaces.go:52:2: may require checklocks annotation for lock, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/config/kube/crdclient
pilot/pkg/config/kube/crdclient/client.go:100:2: may require checklocks annotation for kindsMu, used with lock held 100% of the time
pilot/pkg/config/kube/crdclient/client.go:82:2: may require checklocks annotation for kindsMu, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/config/memory
pilot/pkg/config/memory/store.go:31:2: may require checklocks annotation for mutex, used with lock held 100% of the time
pilot/pkg/config/memory/store.go:65:2: may require checklocks annotation for mutex, used with lock held 100% of the time
pilot/pkg/config/memory/store.go:64:2: may require checklocks annotation for mutex, used with lock held 100% of the time
pilot/pkg/config/memory/store.go:30:2: may require checklocks annotation for mutex, used with lock held 100% of the time
pilot/pkg/config/memory/store.go:33:2: may require checklocks annotation for mutex, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/keycertbundle
pilot/pkg/keycertbundle/watcher.go:82:18: unexpected call to atomic function
pilot/pkg/keycertbundle/watcher.go:116:18: unexpected call to atomic function
pilot/pkg/keycertbundle/watcher.go:37:2: may require checklocks annotation for mutex, used with lock held 100% of the time
pilot/pkg/keycertbundle/watcher.go:35:2: may require checklocks annotation for mutex, used with lock held 100% of the time
pilot/pkg/keycertbundle/watcher.go:33:2: may require checklocks annotation for mutex, used with lock held 100% of the time
pilot/pkg/keycertbundle/watcher.go:36:2: may require checklocks annotation for mutex, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/config/kube/ingress
pilot/pkg/config/kube/ingress/controller.go:90:2: may require checklocks annotation for mutex, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/model/test
pilot/pkg/model/test/mockopenidserver.go:190:21: unexpected call to atomic function
pilot/pkg/model/test/mockopenidserver.go:191:21: unexpected call to atomic function
pilot/pkg/model/test/mockopenidserver.go:202:20: unexpected call to atomic function
pilot/pkg/model/test/mockopenidserver.go:203:20: unexpected call to atomic function
pilot/pkg/model/network_test.go:106:2: may require checklocks annotation for mu, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/serviceregistry/aggregate
pilot/pkg/serviceregistry/aggregate/controller.go:51:2: may require checklocks annotation for storeLock, used with lock held 100% of the time
pilot/pkg/serviceregistry/aggregate/controller.go:48:2: may require checklocks annotation for storeLock, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/serviceregistry/serviceentry
-: return with unexpected locks held (locks: &({param:s}.mutex) exclusively)
-: return with unexpected locks held (locks: &({param:s}.mutex) exclusively)
pilot/pkg/serviceregistry/serviceentry/controller.go:92:2: may require checklocks annotation for mutex, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/serviceregistry/util/workloadinstances
pilot/pkg/serviceregistry/util/workloadinstances/index.go:68:2: may require checklocks annotation for mu, used with lock held 100% of the time
pilot/pkg/serviceregistry/util/workloadinstances/index.go:70:2: may require checklocks annotation for mu, used with lock held 100% of the time
pilot/pkg/serviceregistry/util/workloadinstances/index.go:72:2: may require checklocks annotation for mu, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/status
pilot/pkg/status/resourcelock.go:133:2: may require checklocks annotation for lock, used with lock held 100% of the time
pilot/pkg/status/resourcelock.go:127:2: may require checklocks annotation for lock, used with lock held 100% of the time
pilot/pkg/status/resourcelock.go:135:2: may require checklocks annotation for lock, used with lock held 100% of the time
pilot/pkg/status/resourcelock.go:70:2: may require checklocks annotation for lock, used with lock held 100% of the time
pilot/pkg/status/resourcelock.go:66:2: may require checklocks annotation for lock, used with lock held 100% of the time
pilot/pkg/status/resourcelock.go:136:2: may require checklocks annotation for lock, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/trustbundle
pilot/pkg/trustbundle/trustbundle.go:45:2: may require checklocks annotation for mutex, used with lock held 100% of the time
pilot/pkg/trustbundle/trustbundle.go:47:2: may require checklocks annotation for mutex, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/status/distribution
pilot/pkg/status/distribution/state.go:64:2: may require checklocks annotation for mu, used with lock held 100% of the time
pilot/pkg/status/distribution/state.go:58:2: may require checklocks annotation for mu, used with lock held 100% of the time
pilot/pkg/status/distribution/state.go:59:2: may require checklocks annotation for mu, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/serviceregistry/kube/controller
pilot/pkg/serviceregistry/kube/controller/pod.go:46:2: may require checklocks annotation for RWMutex, used with lock held 100% of the time
pilot/pkg/serviceregistry/kube/controller/endpointslice.go:371:2: may require checklocks annotation for mu, used with lock held 100% of the time
pilot/pkg/serviceregistry/kube/controller/pod.go:38:2: may require checklocks annotation for RWMutex, used with lock held 100% of the time
pilot/pkg/serviceregistry/kube/controller/controller.go:243:2: may require checklocks annotation for RWMutex, used with lock held 100% of the time
pilot/pkg/serviceregistry/kube/controller/pod.go:47:2: may require checklocks annotation for RWMutex, used with lock held 100% of the time
pilot/pkg/serviceregistry/kube/controller/pod.go:41:2: may require checklocks annotation for RWMutex, used with lock held 100% of the time
pilot/pkg/serviceregistry/kube/controller/controller.go:263:2: may require checklocks annotation for RWMutex, used with lock held 100% of the time
pilot/pkg/serviceregistry/kube/controller/controller.go:256:2: may require checklocks annotation for RWMutex, used with lock held 100% of the time
# istio.io/istio/pilot/pkg/xds
pilot/pkg/xds/discovery.go:238:21: unexpected call to atomic function
pilot/pkg/xds/discovery.go:242:27: unexpected call to atomic function
pilot/pkg/xds/bench_test.go:154:39: unexpected call to atomic function
pilot/pkg/xds/monitoring.go:32:2: may require checklocks annotation for xdsClientTrackerMutex, used with lock held 100% of the time
pilot/pkg/xds/discovery.go:129:2: may require checklocks annotation for adsClientsMutex, used with lock held 100% of the time
pilot/pkg/xds/monitoring.go:102:2: may require checklocks annotation for xdsClientTrackerMutex, used with lock held 100% of the time
```

Note that this might be noisy, and you may want to filter out the atomic ("unexpected call to atomic function") and advisory messages ("may require checklocks annotation").

**Comment by amscanne** [comment] 2022-06-15 06:16
Okay, with that I was able to see what's going on. There was an issue with cross-package global mutexes. It was attempting to resolve LastPushMutex in the local package. I've fixed this and added a test. I believe that this issue should now be fixed.

Let me know if you hit other issues. It'll be best effort, but I'm interested to see if checklocks is useful. You'll probably need some kind of filtering (we have this built-in to the way analysis runs). It probably makes sense to disable the "may require", atomic checks and analysis on generated wrappers (the "-" in the above results) by default.

**Comment by amscanne** [comment] 2022-06-15 06:54
I just decided to send a change that makes this behavior configurable (#7731) and close the issue.

With those disabled, the only issue in ./pilot/... is a usage of sync.Mutex in network_test.go. I actually sent istio/istio#39456 to fix this issue, since I think it makes more sense as a sync.WaitGroup.

If I run on the whole repository, there are a few other workflow issues that could be similiar fixed (but that's enough fun for the evening for me):
```
# istio.io/istio/istioctl/cmd
istioctl/cmd/wait_test.go:104:11: {freevar:l} already unlocked or locked differently (locks: no locks held)
istioctl/cmd/wait_test.go:122:2: return with unexpected locks held (locks: {*ssa.Alloc:0xc0042c2900} exclusively)
# istio.io/istio/tools/docker-builder/builder
tools/docker-builder/builder/crane.go:74:17: {global:basesMu} already unlocked or locked differently (locks: no locks held)
# istio.io/istio/pkg/test/framework
pkg/test/framework/analyzer_runtime.go:62:19: {global:analysisMu} already unlocked or locked differently (locks: no locks held)
# istio.io/istio/pkg/test/framework/components/echo/kube
pkg/test/framework/components/echo/kube/workload.go:145:3: return with unexpected locks held (locks: &({param:w}.mutex) exclusively)
pkg/test/framework/components/echo/kube/workload.go:141:20: incompatible return states (first: &({param:w}.mutex) exclusively, second: no locks held)
pkg/test/framework/components/echo/kube/workload_manager.go:175:5: return with unexpected locks held (locks: &({param:m}.mutex) exclusively)
pkg/test/framework/components/echo/kube/workload_manager.go:184:4: return with unexpected locks held (locks: &({param:m}.mutex) exclusively)
pkg/test/framework/components/echo/kube/workload_manager.go:197:3: return with unexpected locks held (locks: &({param:m}.mutex) exclusively)
pkg/test/framework/components/echo/kube/workload_manager.go:205:2: return with unexpected locks held (locks: &({param:m}.mutex) exclusively)
pkg/test/framework/components/echo/kube/workload_manager.go:237:2: return with unexpected locks held (locks: &({param:m}.mutex) exclusively)
```

**Closed** 2022-06-16 15:58 UTC
Labels: type: bug
