### ISSUE TITLE
Memory mapping error on KVM platform

### ISSUE THREAD

**Issue by iwankgb** [google/gvisor#25] opened 2018-05-03 16:14 UTC
Command: 
```
/usr/local/bin/runsc --debug-log-dir=/tmp/runsc --debug --strace --platform=kvm --root /var/run/docker/runtime-runsc/moby --log /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/7ab3f04204712b08eabcf7cd36a2a8b84ee3dca31a9fb736a54ed04636097477/log.json --log-format json state 7ab3f04204712b08eabcf7cd36a2a8b84ee3dca31a9fb736a54ed04636097477
```

Output (truncated, ignoring other goroutines):
```
runtime: address space conflict: map(0xc41ffe0000) = 0xc4419e1000 (err 0)
fatal error: runtime: address space conflict

runtime stack:
runtime.throw(0xb35314, 0x1f)
	GOROOT/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc41ffe0000, 0x8000, 0x100000, 0xfc92d8)
	GOROOT/src/runtime/mem_linux.go:220 +0x1ef
runtime.(*mheap).mapBits(0xfb0800, 0xc420400000)
	GOROOT/src/runtime/mbitmap.go:160 +0xa9
runtime.(*mheap).setArenaUsed(0xfb0800, 0xc420400000, 0xfb0801)
	GOROOT/src/runtime/mheap.go:545 +0x35
runtime.(*mheap).sysAlloc(0xfb0800, 0x100000, 0x7f33ee743c58)
	GOROOT/src/runtime/malloc.go:473 +0x12e
runtime.(*mheap).grow(0xfb0800, 0x1, 0x0)
	GOROOT/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0xfb0800, 0x1, 0xfc9288, 0x7f33ee743c58)
	GOROOT/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0xfb0800, 0x1, 0xfa003c, 0x7f33ee743c58)
	GOROOT/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	GOROOT/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0xfb0800, 0x1, 0x7f33ee01003c, 0x7f33ee743c58)
	GOROOT/src/runtime/mheap.go:752 +0x8a
runtime.(*mcentral).grow(0xfb2a50, 0x0)
	GOROOT/src/runtime/mcentral.go:232 +0x94
runtime.(*mcentral).cacheSpan(0xfb2a50, 0x7f33ee743c58)
	GOROOT/src/runtime/mcentral.go:106 +0x2e4
runtime.(*mcache).refill(0x7f33ee7976c8, 0xc42019a33c)
	GOROOT/src/runtime/mcache.go:123 +0x9c
runtime.(*mcache).nextFree.func1()
	GOROOT/src/runtime/malloc.go:556 +0x32
runtime.systemstack(0x0)
	bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib~/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	GOROOT/src/runtime/proc.go:1175
```

Start log seems to report issue similar to that reported in #11:
```
D0503 18:05:45.842655    4186 x:0] Signal sandbox "7ab3f04204712b08eabcf7cd36a2a8b84ee3dca31a9fb736a54ed04636097477"
D0503 18:05:45.842731    4186 x:0] Start sandbox "7ab3f04204712b08eabcf7cd36a2a8b84ee3dca31a9fb736a54ed04636097477", pid: 4165
D0503 18:05:45.842756    4186 x:0] Executing hook {Path:/proc/1827/exe Args:[libnetwork-setkey 7ab3f04204712b08eabcf7cd36a2a8b84ee3dca31a9fb736a54ed04636097477 dea7bb6eba892c0866b8401cdc7d8cc10889b740f7b53fd650aa22f707b51453] Env:[] Timeout:<nil>}, state: {Version:1.0.1-dev ID:7ab3f04204712b08eabcf7cd36a2a8b84ee3dca31a9fb736a54ed04636097477 Status:created Pid:4165 Bundle:/var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/7ab3f04204712b08eabcf7cd36a2a8b84ee3dca31a9fb736a54ed04636097477 Annotations:map[]}
D0503 18:05:45.885852    4186 x:0] Destroy sandbox "7ab3f04204712b08eabcf7cd36a2a8b84ee3dca31a9fb736a54ed04636097477"
D0503 18:05:45.885953    4186 x:0] Killing sandbox "7ab3f04204712b08eabcf7cd36a2a8b84ee3dca31a9fb736a54ed04636097477"
D0503 18:05:45.885990    4186 x:0] Killing gofer for sandbox "7ab3f04204712b08eabcf7cd36a2a8b84ee3dca31a9fb736a54ed04636097477"
W0503 18:05:45.886227    4186 x:0] FATAL ERROR: error starting sandbox: failure executing hook "/proc/1827/exe", err: exit status 1
stdout: 
stderr: time="2018-05-03T18:05:45+02:00" level=fatal msg="no such file or directory"
```

Content of `/etc/docker/daemon.json`:
```js
{
    "runtimes": {
        "runsc": {
            "path": "/usr/local/bin/runsc",
	    "runtimeArgs": [
                "--debug-log-dir=/tmp/runsc",
                "--debug",
                "--strace",
		"--platform=kvm"
            ]
        }
    }
}
```

`/proc/cpuinfo` (truncated):
```
processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 42
model name	: Intel(R) Core(TM) i5-2557M CPU @ 1.70GHz
stepping	: 7
microcode	: 0x23
cpu MHz		: 797.407
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 2
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm ida arat pln pts
bugs		: cpu_meltdown spectre_v1 spectre_v2
bogomips	: 3390.19
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
```

**Comment by iwankgb** [comment] 2018-05-04 21:14
@prattmic not always, apparetnly. Every dozen or so I can see following error:
```
docker run --runtime=runsc -ti memcached  
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (invalid character ':' looking for beginning of value): /home/docker/runtimes/runsc did not terminate sucessfully: error creating sandbox: timed out waiting for sandbox control server
                                                                                                                                     : unknown.
```
Same erorr can be found in start log:
````
I0504 23:09:42.131540    9345 x:0] ***************************
I0504 23:09:42.131734    9345 x:0] Args: [/usr/local/bin/runsc --debug-log-dir=/tmp/runsc --debug --strace --platform=kvm --root /var/run/docker/runtime-runsc/moby --log /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406/log.json --log-format json create --bundle /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406 --pid-file /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406/init.pid --console-socket /tmp/pty405396838/pty.sock f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406]
I0504 23:09:42.131832    9345 x:0] PID: 9345
I0504 23:09:42.131866    9345 x:0] UID: 0, GID: 0
I0504 23:09:42.131894    9345 x:0] Configuration:
I0504 23:09:42.131919    9345 x:0] 		RootDir: /var/run/docker/runtime-runsc/moby
I0504 23:09:42.131947    9345 x:0] 		Platform: kvm
I0504 23:09:42.132005    9345 x:0] 		FileAccess: proxy, overlay: false
I0504 23:09:42.132042    9345 x:0] 		Network: sandbox, logging: false
I0504 23:09:42.132076    9345 x:0] 		Strace: true, max size: 1024, syscalls: []
I0504 23:09:42.132107    9345 x:0] ***************************
D0504 23:09:42.135461    9345 x:0] Spec: &{Version:1.0.1 Process:0xc4201b8410 Root:0xc4201be3a0 Hostname:f55afe0e3931 Mounts:[{Destination:/proc Type:proc Source:proc Options:[nosuid noexec nodev]} {Destination:/dev Type:tmpfs Source:tmpfs Options:[nosuid strictatime mode=755 size=65536k]} {Destination:/dev/pts Type:devpts Source:devpts Options:[nosuid noexec newinstance ptmxmode=0666 mode=0620 gid=5]} {Destination:/sys Type:sysfs Source:sysfs Options:[nosuid noexec nodev ro]} {Destination:/sys/fs/cgroup Type:cgroup Source:cgroup Options:[ro nosuid noexec nodev]} {Destination:/dev/mqueue Type:mqueue Source:mqueue Options:[nosuid noexec nodev]} {Destination:/etc/resolv.conf Type:bind Source:/home/docker/containers/f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406/resolv.conf Options:[rbind rprivate]} {Destination:/etc/hostname Type:bind Source:/home/docker/containers/f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406/hostname Options:[rbind rprivate]} {Destination:/etc/hosts Type:bind Source:/home/docker/containers/f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406/hosts Options:[rbind rprivate]} {Destination:/dev/shm Type:bind Source:/home/docker/containers/f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406/mounts/shm Options:[rbind rprivate]}] Hooks:0xc420098550 Annotations:map[] Linux:0xc4201d8000 Solaris:<nil> Windows:<nil>}
D0504 23:09:42.135706    9345 x:0] Spec.Hooks: &{Prestart:[{Path:/proc/2855/exe Args:[libnetwork-setkey f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406 5982e436dc7fc268a0ab46079aa560335ec42e2df8896537167245d2f42c946d] Env:[] Timeout:<nil>}] Poststart:[] Poststop:[]}
D0504 23:09:42.135764    9345 x:0] Spec.Linux: &{UIDMappings:[] GIDMappings:[] Sysctl:map[] Resources:0xc420084e40 CgroupsPath:/docker/f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406 Namespaces:[{Type:mount Path:} {Type:network Path:} {Type:uts Path:} {Type:pid Path:} {Type:ipc Path:}] Devices:[] Seccomp:0xc4200a6c00 RootfsPropagation: MaskedPaths:[/proc/kcore /proc/keys /proc/latency_stats /proc/timer_list /proc/timer_stats /proc/sched_debug /proc/scsi /sys/firmware] ReadonlyPaths:[/proc/asound /proc/bus /proc/fs /proc/irq /proc/sys /proc/sysrq-trigger] MountLabel: IntelRdt:<nil>}
D0504 23:09:42.135891    9345 x:0] Spec.Process: &{Terminal:true ConsoleSize:<nil> User:{UID:999 GID:999 AdditionalGids:[] Username:} Args:[docker-entrypoint.sh memcached] Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=f55afe0e3931 TERM=xterm MEMCACHED_VERSION=1.5.7 MEMCACHED_SHA1=31d6f6b80668025e4616aa2ad5c7a45f24ed9665] Cwd:/ Capabilities:0xc420180200 Rlimits:[] NoNewPrivileges:false ApparmorProfile: OOMScoreAdj:0xc4201d22b0 SelinuxLabel:}
D0504 23:09:42.136171    9345 x:0] Spec.Root: &{Path:/home/docker/overlay2/a90116b6553e8deab1a8df6689dc47a3730895c9d3204317f8888f1f3567df8b/merged Readonly:false}
D0504 23:09:42.136232    9345 x:0] Create sandbox "f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406" in root dir: /var/run/docker/runtime-runsc/moby
D0504 23:09:42.136484    9345 x:0] Starting gofer: /usr/local/bin/runsc [--debug=true --debug-log-dir=/tmp/runsc --log=/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406/log.json --log-format=json --platform=kvm --root=/var/run/docker/runtime-runsc/moby --strace=true gofer --bundle /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406 --io-fds=3 --io-fds=4 --io-fds=5 --io-fds=6]
I0504 23:09:42.137173    9345 x:0] Gofer started, pid: 9351
I0504 23:09:42.137887    9345 x:0] Sandbox will be started in empty IPC and UTS namespaces
I0504 23:09:42.137950    9345 x:0] Sandbox will be started in empty PID namespace
I0504 23:09:42.137979    9345 x:0] Sandbox will be started in empty mount namespace
I0504 23:09:42.138032    9345 x:0] Sandbox will be started in the container's network namespace: {Type:network Path:}
I0504 23:09:42.138077    9345 x:0] Sandbox will be started in empty user namespace
D0504 23:09:42.138104    9345 x:0] Starting sandbox: /usr/local/bin/runsc [/usr/local/bin/runsc --debug=true --debug-log-dir=/tmp/runsc --log=/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406/log.json --log-format=json --platform=kvm --root=/var/run/docker/runtime-runsc/moby --strace=true boot --bundle /var/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406 --controller-fd=3 --console=true --io-fds=4 --io-fds=5 --io-fds=6 --io-fds=7]
I0504 23:09:42.141153    9345 x:0] Sandbox started, pid: 9356
D0504 23:09:42.141343    9345 x:0] Waiting for sandbox "f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406" creation
D0504 23:09:52.141503    9345 x:0] Destroy sandbox "f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406"
D0504 23:09:52.141580    9345 x:0] Killing sandbox "f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406"
D0504 23:09:52.141600    9345 x:0] Killing gofer for sandbox "f55afe0e39318331fb0e5238fdee60ab02744651e970a2eea0b5643b559c4406"
W0504 23:09:52.141678    9345 x:0] FATAL ERROR: error creating sandbox: timed out waiting for sandbox control server
````

**Comment by iwankgb** [comment] 2018-05-04 21:27
I also managed to get following error 2 or 3 times:
```
runtime: newstack at runtime.printlock+0x76 sp=0xc4204cd9f8 stack=[0xc420051000, 0xc420052000]
	morebuf={pc:0x4293d3 sp:0xc4204cda00 lr:0x0}
	sched={pc:0x429d66 sp:0xc4204cd9f8 lr:0x0 ctxt:0x0}
runtime.throw(0xb2537f, 0x8)
	GOROOT/src/runtime/panic.go:610 +0x13 fp=0xc4204cda20 sp=0xc4204cda00 pc=0x4293d3
gvisor.googlesource.com/gvisor/pkg/sentry/platform/kvm.bluepillHandler(0xc4204cdac0)
	pkg/sentry/platform/kvm/bluepill_unsafe.go:168 +0x38a fp=0xc4204cdab0 sp=0xc4204cda20 pc=0x81e79a
gvisor.googlesource.com/gvisor/pkg/sentry/platform/kvm.sighandler(0x7, 0x0, 0xc4204c6000, 0x0, 0x8000, 0xc42008c418, 0xc42008c498, 0x1, 0xc42008c410, 0xc42008c410, ...)
	pkg/sentry/platform/kvm/bluepill_amd64.s:79 +0x24 fp=0xc4204cdac0 sp=0xc4204cdab0 pc=0x82c254
runtime: unexpected return pc for runtime.sigreturn called from 0x7
stack: frame={sp:0xc4204cdac0, fp:0xc4204cdac8} stack=[0xc420051000,0xc420052000)

runtime.sigreturn(0x0, 0xc4204c6000, 0x0, 0x8000, 0xc42008c418, 0xc42008c498, 0x1, 0xc42008c410, 0xc42008c410, 0x0, ...)
	bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib~/src/runtime/sys_linux_amd64.s:444 fp=0xc4204cdac8 sp=0xc4204cdac0 pc=0x457340
created by gvisor.googlesource.com/gvisor/pkg/sentry/kernel.(*Task).Start
	pkg/sentry/kernel/task_start.go:251 +0x100
fatal error: runtime: stack split at bad time

runtime stack:
runtime.throw(0xb35d4b, 0x20)
	GOROOT/src/runtime/panic.go:616 +0x81 fp=0xc4204b3e48 sp=0xc4204b3e28 pc=0x429441
runtime.newstack()
	GOROOT/src/runtime/stack.go:954 +0xb61 fp=0xc4204b3fd8 sp=0xc4204b3e48 pc=0x442821
runtime.morestack()
	bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib~/src/runtime/asm_amd64.s:480 +0x89 fp=0xc4204b3fe0 sp=0xc4204b3fd8 pc=0x453669

goroutine 46 [syscall, locked to thread]:
runtime.throw(0xb2537f, 0x8)
	GOROOT/src/runtime/panic.go:610 +0x13 fp=0xc4204cda20 sp=0xc4204cda00 pc=0x4293d3
gvisor.googlesource.com/gvisor/pkg/sentry/platform/kvm.bluepillHandler(0xc4204cdac0)
	pkg/sentry/platform/kvm/bluepill_unsafe.go:168 +0x38a fp=0xc4204cdab0 sp=0xc4204cda20 pc=0x81e79a
gvisor.googlesource.com/gvisor/pkg/sentry/platform/kvm.sighandler(0x7, 0x0, 0xc4204c6000, 0x0, 0x8000, 0xc42008c418, 0xc42008c498, 0x1, 0xc42008c410, 0xc42008c410, ...)
	pkg/sentry/platform/kvm/bluepill_amd64.s:79 +0x24 fp=0xc4204cdac0 sp=0xc4204cdab0 pc=0x82c254
runtime: unexpected return pc for runtime.sigreturn called from 0x7
stack: frame={sp:0xc4204cdac0, fp:0xc4204cdac8} stack=[0xc420051000,0xc420052000)

runtime.sigreturn(0x0, 0xc4204c6000, 0x0, 0x8000, 0xc42008c418, 0xc42008c498, 0x1, 0xc42008c410, 0xc42008c410, 0x0, ...)
	bazel-out/k8-fastbuild/bin/external/io_bazel_rules_go/linux_amd64_pure_stripped/stdlib~/src/runtime/sys_linux_amd64.s:444 fp=0xc4204cdac8 sp=0xc4204cdac0 pc=0x457340
created by gvisor.googlesource.com/gvisor/pkg/sentry/kernel.(*Task).Start
	pkg/sentry/kernel/task_start.go:251 +0x100
```
You can find all 10 log files generated during this run at: https://critical.today/files/newstack.tar.bz2.

**Comment by iwankgb** [comment] 2018-05-04 21:29
I also managed to run the container succussfully (twice out of ~50 attempts). See logs at https://critical.today/files/successfull.tar.bz2.

**Comment by prattmic** [comment] 2018-05-04 23:06
That error is the same as #11, so it looks like these are related. Let's merge the two issues.

Duplicate of #11

**Comment by prattmic** [comment] 2018-05-04 23:06
Duplicate of #11

**Closed** 2018-05-09 17:10 UTC
