### ISSUE TITLE
Failed to run portainer

### ISSUE THREAD

**Issue by chanwit** [google/gvisor#33] opened 2018-05-04 11:53 UTC
When running Portainer (`portainer/portainer`) with volume binding, the container cannot be started.

- `docker version` or `docker info` if more relevant
Docker 18.03.1

- `uname -a`
```
Linux ip-172-31-23-9 4.4.0-1049-aws #58-Ubuntu SMP Fri Jan 12 23:17:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Full docker command you ran
`docker run -p 9000:9000 --privileged -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer`

Error log from Docker daemon:
```
returned error: OCI runtime create failed: unable to retrieve OCI runtime error (invalid character 'm' after object key)
```

Log files:
[runsc.log.20180504-113618.395832.boot.txt](https://github.com/google/gvisor/files/1974293/runsc.log.20180504-113618.395832.boot.txt)
[runsc.log.20180504-113618.393880.gofer.txt](https://github.com/google/gvisor/files/1974296/runsc.log.20180504-113618.393880.gofer.txt)
[runsc.log.20180504-113618.383749.create.txt](https://github.com/google/gvisor/files/1974297/runsc.log.20180504-113618.383749.create.txt)

**Comment by fvoznika** [comment] 2018-05-04 17:17
Part of this is fixed with commit 5376cd4 (typo and missing capability).

The other part is what you're trying to do is incompatible with the sandbox model. `--privileged` option is to give the container access to the host machine and mapping of unix domain socket inside the sandbox is explicitly prohibited to keep the isolation.

**Comment by chanwit** [comment] 2018-05-05 08:44
Thank you @fvoznika. I'll try another option, like connecting to the target Docker engine via TCP.
It may raise another issue, but I'll try to address them one-by-one. I'll back to you shortly with some more updates.

**Comment by chanwit** [comment] 2018-05-05 15:12
I compiled a new binary from today's commit, and narrowed the test case.

1. run `docker run --runtime=runsc -p 9000:9000 portainer/portainer --no-auth --no-analytics -H tcp://127.0.0.1:2375`
2. do `curl http://127.0.0.1:9000/js/app.bb4cea25.js > js`.
This URL is a large minified JS file. It seems there are somethings at the network layer prevented it from being fully read.
I ran curl many times, and here's the logs.
```
$ curl http://127.0.0.1:9000/js/app.bb4cea25.js > x
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 93 2226k   93 2080k    0     0  3971k      0 --:--:-- --:--:-- --:--:-- 3970k
curl: (18) transfer closed with 149360 bytes remaining to read

$ curl http://127.0.0.1:9000/js/app.bb4cea25.js > y
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 94 2226k   94 2101k    0     0  3902k      0 --:--:-- --:--:-- --:--:-- 3898k
curl: (18) transfer closed with 127640 bytes remaining to read

$ curl http://127.0.0.1:9000/js/app.bb4cea25.js > z
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 94 2226k   94 2103k    0     0  3985k      0 --:--:-- --:--:-- --:--:-- 3984k
curl: (18) transfer closed with 125280 bytes remaining to read
```

**Comment by iangudger** [comment] 2018-05-05 16:29
@chanwit, Can you upload some new logs?

**Comment by chanwit** [comment] 2018-05-06 05:58
@iangudger please file the logs below.

[runsc.log.20180506-125421.107544.create.txt](https://github.com/google/gvisor/files/1977373/runsc.log.20180506-125421.107544.create.txt)
[runsc.log.20180506-125421.113868.gofer.txt](https://github.com/google/gvisor/files/1977374/runsc.log.20180506-125421.113868.gofer.txt)
[runsc.log.20180506-125421.114533.boot.txt](https://github.com/google/gvisor/files/1977375/runsc.log.20180506-125421.114533.boot.txt)
[runsc.log.20180506-125421.124902.state.txt](https://github.com/google/gvisor/files/1977376/runsc.log.20180506-125421.124902.state.txt)
[runsc.log.20180506-125421.129732.start.txt](https://github.com/google/gvisor/files/1977377/runsc.log.20180506-125421.129732.start.txt)
[runsc.log.20180506-125421.292836.state.txt](https://github.com/google/gvisor/files/1977378/runsc.log.20180506-125421.292836.state.txt)
[runsc.log.20180506-125629.221492.kill.txt](https://github.com/google/gvisor/files/1977379/runsc.log.20180506-125629.221492.kill.txt)
[runsc.log.20180506-125629.272299.kill.txt](https://github.com/google/gvisor/files/1977380/runsc.log.20180506-125629.272299.kill.txt)
[runsc.log.20180506-125629.329834.state.txt](https://github.com/google/gvisor/files/1977381/runsc.log.20180506-125629.329834.state.txt)
[runsc.log.20180506-125629.335755.kill.txt](https://github.com/google/gvisor/files/1977382/runsc.log.20180506-125629.335755.kill.txt)
[runsc.log.20180506-125629.340082.delete.txt](https://github.com/google/gvisor/files/1977383/runsc.log.20180506-125629.340082.delete.txt)

**Comment by dlorenc** [comment] 2018-05-06 13:10
@fvoznika can you clarify whether or not volume mounts are expected to work with gvisor?

**Comment by chanwit** [comment] 2018-05-11 10:47
@fvoznika @iangudger could you give some hints where should I start to take a look to find cause of this issue?

**Comment by chanwit** [comment] 2018-05-11 16:16
Tested with and without  `--network=host`, results are the same.

**Comment by fvoznika** [comment] 2018-05-11 17:16
@dlorenc, yes volume mounts work with gVisor.

@chanwit, sorry I haven't had a chance to look into this yet. I was able to repro it locally though.

**Comment by chanwit** [comment] 2018-05-12 07:43
@fvoznika thank you. Glad to know that you could reproduce it.

**Comment by chanwit** [comment] 2018-05-15 14:26
Updated:
I did `runsc` directly with a Docker generated `config.json` (attached), manually extracted bundle with `--network=host` and Portainer was working correctly.

The bundle extracted using the following command:
`docker export $(docker create portainer/portainer) | tar -C ~/rootfs -xvf -`

[config.json.txt](https://github.com/google/gvisor/files/2005356/config.json.txt)

So this issue could be narrowed down to the networking layer (proxy mode).

**Comment by fvoznika** [comment] 2018-05-15 14:58
Thanks for the update. The problem is with our sendfile(2) implementation when more data is read than can be written. I have a fix in code review...should be out shortly.

**Closed** 2018-05-15 21:39 UTC
