### ISSUE TITLE
how to build gvisor in arm64 

### ISSUE THREAD

**Issue by magnate3** [google/gvisor#5168] opened 2020-12-24 12:26 UTC
**Description**

A clear description of what the bug is. If possible, explicitly indicate the
expected behavior vs. the observed behavior.

**Steps to reproduce**
root@cloud:~/gvisor# make -j $(nproc)
warning: /var/cache/dnf/docker-ce-stable-5216070ebe39d4d5/packages/docker-ce-cli-20.10.1-3.fc31.aarch64.rpm: Header V4 RSA/SHA512 Signature, key ID 621e9f35: NOKEY
Docker CE Stable - aarch64                      0.0  B/s |   0  B     00:00    
Curl error (35): SSL connect error for https://download.docker.com/linux/fedora/gpg [OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to download.docker.com:443 ]
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
The command '/bin/sh -c dnf install -y docker-ce-cli' returned a non-zero code: 1
--- BUILD -c opt //runsc
**Error: No such container: gvisor-bazel-3328c4e9-aarch64**

**Environment**

 root@cloud:~/gvisor# uname -a
Linux cloud 5.5.19-050519-generic #202004210831 SMP Tue Apr 21 08:49:56 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
root@cloud:~/gvisor# 

the problem mybe fail to install google-cloud-sdk

**Comment by adamliyi** [comment] 2021-01-11 07:50
@magnate3 , This is not a bug. 
Looks this error log indicates you cannot install docker-ce-cli.

To install gVisor from source on ARM64, please refer to: https://github.com/google/gvisor/blob/master/README.md#installing-from-source
or:
https://github.com/AmpereComputing/gVisor-on-ampere

Basically we need to install bazel firstly, then build gVisor.

Recently gVisor add support to install aarch64 gvisor binaries (nightly, head) (https://github.com/google/gvisor/commit/0c99ab70905fa4eaf8bc7b0ca846e12d7bbc6e39), but it does not fully work yet.

**Comment by adamliyi** [comment] 2021-01-11 07:52
Suggests to close this issue.

**Closed** 2021-01-11 08:02 UTC
Labels: type: bug
