### ISSUE TITLE
'docker cp' can't copy file into container after 'docker exec' operation.

### ISSUE THREAD

**Issue by davidchen8319** [google/gvisor#3137] opened 2020-07-03 09:53 UTC
**Description**
'docker cp' can't copy file into container after 'docker exec' operation.

**Steps to reproduce**
```
chy@ubuntu:~$ docker run -d   --tmpfs /myapp --name gvisor-analysis  --runtime=runsc gcc:4.9 sleep 360000
8f089e62ecd1882df28a7b583e8eabf95279e1c9cd14c732e23e835d59ac194e
chy@ubuntu:~$ docker cp gvisor_analysis/experiments/execute/write_throughput/write gvisor-analysis:/write
chy@ubuntu:~$ docker cp gvisor_analysis/experiments/execute/write_throughput/write gvisor-analysis:/write2
chy@ubuntu:~$ docker exec -it gvisor-analysis ls /
bin  boot  dev	etc  home  lib	lib64  media  mnt  myapp  opt  proc  root  run	sbin  srv  sys	tmp  usr  var  write  write2
```
note: 'write  write2' is listed.  continue next step.

```
chy@ubuntu:~$ docker cp gvisor_analysis/experiments/execute/write_throughput/write gvisor-analysis:/write3
chy@ubuntu:~$ docker exec -it gvisor-analysis ls /
bin  boot  dev	etc  home  lib	lib64  media  mnt  myapp  opt  proc  root  run	sbin  srv  sys	tmp  usr  var  write  write2
```

note: write3 is missing.

**Environment**

Please include the following details of your environment:

*   `runsc -v`
runsc version release-20200622.1-59-g6c099d830091-dirty
spec: 1.0.1-dev

*   `docker version` or `docker info` (if available)
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

*   `uname -a`
Linux ubuntu 5.3.0-61-generic #55~18.04.1-Ubuntu SMP Mon Jun 22 16:40:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

*   `git describe` (if built from source)
release-20200622.1-59-g6c099d830

*   `runsc` debug logs (if available)

**Comment by ianlewis** [comment] 2020-07-06 01:40
This is a duplicate of #4

See: https://gvisor.dev/docs/user_guide/FAQ/#fs-cache

**Closed** 2020-07-06 01:40 UTC
