### ISSUE TITLE
installing packages not possible: no user _apt, or cannot open file

### ISSUE THREAD

**Issue by mirabilos** [google/gvisor#150] opened 2019-03-25 17:30 UTC
Similar to #149 and in the same environment.

I restarted a fresh `debian:buster` session and installed some packages as I went. Then I realised I need the full perl, and get:

```
root@5e76e9ba85bc:/usr/share/doc/mksh# apt-get install perl
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libgdbm-compat4 libgdbm6 libperl5.28 netbase perl-modules-5.28
Suggested packages:
  gdbm-l10n sensible-utils perl-doc libterm-readline-gnu-perl | libterm-readline-perl-perl make libb-debug-perl
  liblocale-codes-perl
The following NEW packages will be installed:
  libgdbm-compat4 libgdbm6 libperl5.28 netbase perl perl-modules-5.28
0 upgraded, 6 newly installed, 0 to remove and 19 not upgraded.
Need to get 7096 kB of archives.
After this operation, 47.1 MB of additional disk space will be used.
Do you want to continue? [Y/n]
E: Method gave invalid 400 URI Failure message: No user _apt, can not drop rights
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)
root@5e76e9ba85bc:/usr/share/doc/mksh# id _apt
uid=100(_apt) gid=65534(nogroup) groups=65534(nogroup)
root@5e76e9ba85bc:/usr/share/doc/mksh# ps ax
bash: ps: command not found
root@5e76e9ba85bc:/usr/share/doc/mksh# cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
root@5e76e9ba85bc:/usr/share/doc/mksh# apt-get install perl
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libgdbm-compat4 libgdbm6 libperl5.28 netbase perl-modules-5.28
Suggested packages:
  gdbm-l10n sensible-utils perl-doc libterm-readline-gnu-perl | libterm-readline-perl-perl make libb-debug-perl
  liblocale-codes-perl
The following NEW packages will be installed:
  libgdbm-compat4 libgdbm6 libperl5.28 netbase perl perl-modules-5.28
0 upgraded, 6 newly installed, 0 to remove and 19 not upgraded.
Need to get 7096 kB of archives.
After this operation, 47.1 MB of additional disk space will be used.
Do you want to continue? [Y/n]
0% [Working]/usr/lib/apt/methods/http: error while loading shared libraries: libffi.so.6: cannot open shared object file: Error 24
0% [Working]
```

I think something with file access is broken in gvisor. (I admit I did not try without runsc, but can do if necessary.)

**Comment by fvoznika** [comment] 2019-03-26 01:07
Can you repro it? I ran it locally and it worked. Maybe it has to do with some of the packages you installed before?

```
> docker run --runtime=runsc -it debian:buster bash
root@86ae38580f8c:/# apt-get update && apt-get install perl -y
Get:1 http://security-cdn.debian.org/debian-security buster/updates InRelease [38.3 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian buster InRelease [158 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease [46.8 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages [7886 kB]
Fetched 8130 kB in 9s (886 kB/s)                                                                                       
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libgdbm-compat4 libgdbm6 libperl5.28 netbase perl-modules-5.28
Suggested packages:
  gdbm-l10n sensible-utils perl-doc libterm-readline-gnu-perl | libterm-readline-perl-perl make libb-debug-perl
  liblocale-codes-perl
The following NEW packages will be installed:
  libgdbm-compat4 libgdbm6 libperl5.28 netbase perl perl-modules-5.28
0 upgraded, 6 newly installed, 0 to remove and 19 not upgraded.
Need to get 7096 kB of archives.
After this operation, 47.1 MB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian buster/main amd64 perl-modules-5.28 all 5.28.1-4 [2874 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libgdbm6 amd64 1.18.1-4 [64.7 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libgdbm-compat4 amd64 1.18.1-4 [44.1 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian buster/main amd64 libperl5.28 amd64 5.28.1-4 [3890 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian buster/main amd64 perl amd64 5.28.1-4 [204 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian buster/main amd64 netbase all 5.6 [19.4 kB]
Fetched 7096 kB in 1s (9279 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package perl-modules-5.28.
(Reading database ... 6649 files and directories currently installed.)
Preparing to unpack .../0-perl-modules-5.28_5.28.1-4_all.deb ...
Unpacking perl-modules-5.28 (5.28.1-4) ...
Selecting previously unselected package libgdbm6:amd64.
Preparing to unpack .../1-libgdbm6_1.18.1-4_amd64.deb ...
Unpacking libgdbm6:amd64 (1.18.1-4) ...
Selecting previously unselected package libgdbm-compat4:amd64.
Preparing to unpack .../2-libgdbm-compat4_1.18.1-4_amd64.deb ...
Unpacking libgdbm-compat4:amd64 (1.18.1-4) ...
Selecting previously unselected package libperl5.28:amd64.
Preparing to unpack .../3-libperl5.28_5.28.1-4_amd64.deb ...
Unpacking libperl5.28:amd64 (5.28.1-4) ...
Selecting previously unselected package perl.
Preparing to unpack .../4-perl_5.28.1-4_amd64.deb ...
Unpacking perl (5.28.1-4) ...
Selecting previously unselected package netbase.
Preparing to unpack .../5-netbase_5.6_all.deb ...
Unpacking netbase (5.6) ...
Setting up perl-modules-5.28 (5.28.1-4) ...
Setting up netbase (5.6) ...
Setting up libgdbm6:amd64 (1.18.1-4) ...
Setting up libgdbm-compat4:amd64 (1.18.1-4) ...
Setting up libperl5.28:amd64 (5.28.1-4) ...
Setting up perl (5.28.1-4) ...
Processing triggers for libc-bin (2.28-7) ...
root@86ae38580f8c:/#
```

**Comment by amscanne** [comment] 2019-03-26 01:13
> error while loading shared libraries: libffi.so.6: cannot open shared object file: Error 24

Error 24 is EMFILE, which indicates that we're probably hitting the same case as in #149. I suspect that in your setup you have a lower RLIMIT_NOFILE and we're not handling the case properly where that limit is hit. (Error just propagating through to the application.)

**Comment by mirabilos** [comment] 2019-03-26 10:34
Adin Scannell dixit:

>Error 24 is EMFILE, which indicates that we're probably hitting the
>same case as in #149. I suspect that in your setup you have a lower
>RLIMIT_NOFILE and we're not handling the case properly where that
>limit is hit. (Error just propagating through to the application.)

The default “ulimit -n” inside Docker seems to be 1048756, which
comes over as a bit high. But even if I lower it to 512, the error
occurs.

**Comment by fvoznika** [comment] 2019-03-26 17:21
This is hitting the issue in #149. The Sentry is not closing files properly and eventually the file limit is hit in the host. To workaround it, you would need to increase RLIMIT_NOFILE outside the sandbox. More details in #149. Thanks for the report!

**Comment by fvoznika** [comment] 2019-03-26 17:22
Duplicate of #149

**Closed by fvoznika** 2019-03-26 17:21 UTC
