### ISSUE TITLE
installing packages not possible: “too many open files”

### ISSUE THREAD

**Issue by mirabilos** [google/gvisor#149] opened 2019-03-25 17:23 UTC
I’ve (now on an amd64 VM) tried to install build-essential and other packages into a debian:buster container/image(?), and it failed:

```
# docker run --runtime=runsc -it debian:buster /bin/bash
root@9ef40df80df7:/# apt-get update
[…]
root@9ef40df80df7:/# apt-get install build-essential bsdmainutils debhelper ed dietlibc-dev libklibc-dev musl-tools locales devscripts
[…]
Unpacking libc6:amd64 (2.28-8) over (2.28-7) ...
dpkg: error processing archive /var/cache/apt/archives/libc6_2.28-8_amd64.deb (--unpack):
 unable to create '/lib/x86_64-linux-gnu/libnss_dns-2.28.so.dpkg-new' (while processing './lib/x86_64-linux-gnu/libnss_dns-2.28.so'): Too many open files
dpkg-deb (subprocess): decompressing archive member: lzma write error: Broken pipe
dpkg-deb (subprocess): cannot copy archive member from '/var/cache/apt/archives/libc6_2.28-8_amd64.deb' to decompressor pipe: failed to write (Broken pipe)
dpkg-deb: error: <decompress> subprocess returned error exit status 2
Errors were encountered while processing:
 /var/cache/apt/archives/libc6_2.28-8_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

In a previous attempt, another file was affected, and it led to curious things:

```
root@b20719de5072:/# ls -la /usr/lib/x86_64-linux-gnu/gconv
ls: cannot access '/usr/lib/x86_64-linux-gnu/gconv/CP1125.so.dpkg-new': No such file or directory
total 16
drwxr-xr-x 2 root root 12288 Mar 25 17:15 .
drwxr-xr-x 8 root root  4096 Mar 25 17:16 ..
-????????? ? ?    ?        ?            ? CP1125.so.dpkg-new
```

It also failed when I tried `ulimit -n 512` before the `apt-get install` call.

----

Other useful information to include is:

```
# uname -a
Linux XXXredactedXXX.lan.tarent.de 4.19.0-3-amd64 #1 SMP Debian 4.19.20-1 (2019-02-11) x86_64 GNU/Linux
# docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.5
 Git commit:        4c52b90
 Built:             Mon, 11 Mar 2019 00:06:03 +0000
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.5
  Git commit:       4c52b90
  Built:            Mon Mar 11 00:06:03 2019
  OS/Arch:          linux/amd64
  Experimental:     false
# docker info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 1
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc runsc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 1.0.0~rc6+dfsg1-3
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.19.0-3-amd64
Operating System: Debian GNU/Linux buster/sid
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.792GiB
Name: XXXredactedXXX.lan.tarent.de
ID: 6LF3:RSNI:RK6U:GZPD:QOBI:T27U:R5Y6:FIAT:74B4:BNQX:4D7N:BJG3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by fvoznika** [comment] 2019-03-26 17:16
The problem here is that the Sentry (gVisor's kernel) is not closing files properly (most likely a refcount problem). After `apt-get install` above returns, there are still 438 open files. The effect is worse on the gofer, because when a file is opened for write, it keeps both control and new file around which is not necessary anymore.

Until we fix it, you can workaround it by increasing RLIMIT_NOFILE outside the sandbox. `containerd` is the process that starts gVisor, so you can change it there:

`sudo prlimit --pid $(pgrep ^containerd$) --nofile=1048576:1048576`

**Comment by amscanne** [comment] 2019-03-26 17:24
You sure it's a leak? There is a dirent cache. Just seems likely that it's not handling a smaller limit gracefully.

**Comment by fvoznika** [comment] 2019-03-26 17:33
Not, I'm not sure. I didn't track down where there are coming from. It could indeed be from the dirent cache.

**Comment by fvoznika** [comment] 2019-03-26 18:01
You're right. If I drop size of dirent cache from 1000 (default) to 10, the number of open FDs drop to 38. So we need to make the dirent cache aware of the limit (and apply the host limit to the sandbox).

**Comment by D-Nice** [comment] 2019-03-27 23:44
I've encountered similar "too many open files" with alpine and running `npm install` for example on a nodejs repo.

**Comment by chuangxueli** [comment] 2019-03-30 03:44
hi,
I have also encountered  this issue. There may be some FD leak issues in the gofer
I used cypthon to test in gvisor ,and also merge your patch,but the issue still exists.I wrote one simple test  to verify this case .In the test,I open one file,and  do the reading,
then close it.at the same time I use isof  to see the the process gofer,the result is that ,there are more files pending to be closed.
My test steps are below:
1,sudo docker run --runtime=runsc  -it -v /fd_leak_test:/test   ubuntu /bin/bash
2,in the test directory  do the open and close testing
I checked the codes in pkg/sentry/fs/gofer,found that the when open one file with O_RDONLY flag,the getCachedHandles will increase the handler reference for the first time,but when it closes this file,it only return in the (*handles).DecRef,because the reference of the handles is not zero.In the second open ,it use the cachepolicy to get the handles,it doesn't increase the reference of the handle,so when do the FileOperations.Release,it can close the file.In the all testing,I found the (*inodeOperations.)Release was not called ,the FD was not released
So,would you please confirmed that ?
thanks
 chuangxue

**Comment by chuangxueli** [comment] 2019-04-01 04:39
@fvoznika 
Hi,fvoznika
Is there any update for this issue?
thanks
chuangxueli

**Comment by fvoznika** [comment] 2019-04-02 16:06
@chuangxueli, the sentry has a cache that saves the last 1000 dirent entries touched by the application. So when the application closes a file, it may not close the file from the underlying host. This includes the file and the directories used to walk to the file. This speeds up dir/file look up quite a bit.

For example, If you run `cat /etc/passwd` and then look at `ls -l /prod/[gofer-pid]/fd` you'll see that `/bin/cat`, all its libraries (e.g. libc.so), and `/etc/passwd` are all still open, together with their paths: `/bin`, `\etc`. If you need to use any of these dir/files again, they come straight from the cache and don't need to be reopened. You will also note that some files have 2 FDs:

```
sudo ls -lh /proc/[gofer-pid]/fd | sed 's/.*-> //' | sort | uniq -c | sort -n -r
      [...]
      2 /root/etc/passwd
      2 /root/bin/cat
      1 /root/etc
      1 /root/bin
      [...]
```
Unopened files have a single FD, which corresponds to `gofer.inodeFileState.file`. This is an unopened gofer file that is used as source when the inode needs opened a file for read and/or write. Files that are opened will have 2 FDs (there may be more depending on caching mode). One for `gofer.inodeFileState.file` and another one for the handle as you noted above.

The commit beb71ab681dadb2eed3407bc9188bfe85694eb22 was rolled back due to a bug, and redone with the fix in 1df3fa69977477092efa65a8de407bd6f0f88db4. This change reduced in half the number of FDs used by the gofer. There are a few more changes coming up that will help with `too many open files` error. But in general, gVisor requires more FDs than a native process would. For the reasons noted above and also because the same sandbox process must be able to open files for all the processes running inside it.

**Comment by chuangxueli** [comment] 2019-04-17 03:43
hi，fvoznika 
Thanks for your comments，and now we want to launch more applications in the gvisor,so the FDs in gofer are more than other processes in the host.This will give the big pressure for the host if  we create more containers via gvisor.So can you give some proposal to close the FDs when we do the close one openned file?
For example,base on the commit 1df3fa6,how can we close the files which we have openned and done the read  absolutely?
thanks
chuangxueli

**Comment by fvoznika** [comment] 2019-04-17 16:37
There is an [upcoming change](https://gvisor-review.googlesource.com/c/gvisor/+/16508) that will add a global limit to the dirent cache and make the cache limit based on the host `RLIMIT_NOFILE` setting. That would allow you to limit the number of FDs used by gVisor.

There is also another change I'm working on to send pressure notification to dirent caches when the limit is reached. It will shrink the caches and allow the operation to succeed. I didn't get much time to work on it, but I'll make it higher priority.

**Comment by amscanne** [comment] 2019-04-17 16:40
@chuangxueli What's the concern about pressure in the host? The incremental cost of each FD is hopefully marginal with respect to host costs. What's the concern beyond the limits?

**Comment by chuangxueli** [comment] 2019-04-18 02:22
@fvoznika good！we are reviewing the RLIMIT_NOFILE  patch,that 's help .And before the patch merged to master branch, we'll disable the direct  cache for our testing ,thanks

**Comment by chuangxueli** [comment] 2019-04-18 02:29
@amscanne Base on the current  code,we bring up more gvisors in host,so the they will cosume more FDs.When we do other applications testing,the FDs may be shortage which cause the apps get errors.So when the RLIMIT_NOFILE  patch released,that will be more helpful.

**Closed** 2021-06-09 17:22 UTC
Labels: area: filesystem, type: bug

**Comment by mirabilos** [comment] 2021-06-09 17:34
So… is this fixed now or what? Just closing without a status update message is… not very helpful.

**Comment by fvoznika** [comment] 2021-06-09 23:25
There were a few fixes mentioned in comments above, like reducing the number of FDs used across the board. More importantly we now size the dirent cache based on `RLIMIT_NOFILE` to avoid having the cache trip over the limit. If you still see problems, feel free to reopen it.

**Comment by mirabilos** [comment] 2021-06-10 10:22
Fabricio Voznika dixit:

>There were a few fixes mentioned in comments above, like reducing the

Ah, okay. I thought they were just being discussed by mentioning them
above, but if they are implemented now, great.

Thanks,
//mirabilos
-- 
  "Using Lynx is like wearing a really good pair of shades: cuts out
   the glare and harmful UV (ultra-vanity), and you feel so-o-o COOL."
                                         -- Henry Nelson, March 1999
