### ISSUE TITLE
Error: `unable to retrieve OCI runtime error (open /var/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/.../log.json: no such file or directory):`

### ISSUE THREAD

**Issue by infokiller** [google/gvisor#5865] opened 2021-04-21 13:57 UTC
**Description**

After installing the latest runsc following https://gvisor.dev/docs/user_guide/install/#install-latest I'm unable to use it with docker:

```sh
❯ sudo docker run --rm --runtime=runsc hello-world
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /var/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/c08f9cc7a27226260fa5781ad28ad10eb3d5aca07bb22bc43b9ea74675ed0981/log.json: no such file or directory): /usr/local/bin/runsc did not terminate successfully: unknown.
```

Not sure if this is related, but this also fails:

```sh
❯ sudo runsc do echo
creating container: cgroups V2 is not yet supported. Enable cgroups V1 and retry
```

**Steps to reproduce**

If available, please include detailed reproduction steps.

If the bug requires software that is not publicly available, see if it can be
reproduced with software that is publicly available.

**Environment**

Please include the following details of your environment:

*   `runsc -version`

```sh
❯ runsc --version
runsc version release-20210419.0
spec: 1.0.2
```

*   `docker version` or `docker info` (if available)

<details>
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 65
  Running: 0
  Paused: 0
  Stopped: 65
 Images: 615
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc runsc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e.m
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.11.14-hardened1-1-hardened
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 94GiB
 Name: desk18
 ID: AFTR:LS7E:PE3L:A6BO:LJCW:IN75:6VFX:KHWW:ZUHL:KGKD:6MXN:C3RS
 Docker Root Dir: /mnt/evo970/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
</details>

*   `kubectl version` and `kubectl get nodes` (if using Kubernetes)

*   `uname -a`
`Linux 5.11.14-hardened1-1-hardened`

*   `git describe` (if built from source)
*   `runsc` debug logs (if available)

**Comment by fvoznika** [comment] 2021-04-21 22:42
Yes, the problem is that your machine has only cgroups v2 enabled. gVisor only supports cgroups v1. If you search for `revert cgroup v1` you'll find instructions to revert it based on your distribution.

**Comment by fvoznika** [comment] 2021-04-21 22:42
Duplicate of #3481

**Closed by fvoznika** 2021-04-21 22:42 UTC
Labels: type: bug
