### ISSUE TITLE
simple commands failed due to sort of IOCTL-related problems

### ISSUE THREAD

**Issue by StanPlatinum** [google/gvisor#3045] opened 2020-06-20 04:02 UTC
**Description**

When I run the most common ubuntu:18.04 container using the latest runsc, some unexpected bugs occurred. The command **_apt_** didn't work properly. It seems that the IOCTL fails and some segmentation faults happened.

Critical logs like the following:
_E: Setting TIOCSCTTY for slave fd 23 failed! - ioctl (1: Operation not permitted)_

This won't happen on runc cases.

**Steps to reproduce**

```
docker run -it --runtime=runsc --memory=4000m ubuntu:18.04
apt install vim -y
```

**Environment**

Please include the following details of your environment:

*  runsc --version:
runsc version release-20200608.0-100-gf46f4a2af98a
spec: 1.0.1-dev

*  docker version:
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:22 2020
 OS/Arch:           linux/amd64
 Experimental:      false

*  Server: 
 Docker Engine - Community
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       42e35e61f3
  Built:            Mon Jun  1 09:10:54 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

*  uname -a:
Linux warthog 5.3.0-59-generic #53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

*  git describe:
release-20200608.0-100-gf46f4a2af

**Comment by hbhasker** [comment] 2020-06-20 15:45
That seems like a regression. Thanks for the report. @kevinGC could you take a look?

**Comment by kevinGC** [comment] 2020-06-22 17:13
@StanPlatinum can you clarify whether apt failed or just produced the error output? I am able to run your repro steps (with an added `apt-get update` before installation), and despite seeing the error about `TIOCSCTTY`, installation completes and vim usable.

If you're interested in the root cause of the error output: you can see [here](https://github.com/google/gvisor/blob/master/pkg/sentry/fs/host/tty.go#L279) that `TIOCSCTTY` hasn't been implemented on host TTYs (what gets used with `docker run -it`).

**Comment by StanPlatinum** [comment] 2020-06-23 07:31
@kevinGC Thanks! 

Yes, the apt produced the error output but not failed.

**Comment by hbhasker** [comment] 2020-06-24 14:59
Kevin can we close this report as there is already one for the main issue that causes the confusion?

**Comment by kevinGC** [comment] 2020-09-02 18:33
Leaving this open -- I closed the other bug because this thread has more detailed explanation. This is something I'd like to see done, but it looks like it's only an inconvenience ATM.

**Closed** 2023-09-18 09:45 UTC
Labels: type: bug, priority: p3, area: tty

**Comment by nlacasse** [comment] 2023-11-07 17:36
Should be fixed by https://github.com/google/gvisor/pull/9647
