### ISSUE TITLE
incoming multicast is filtered only at the NIC

### ISSUE THREAD

**Issue by tamird** [google/gvisor#3931] opened 2020-09-13 16:00 UTC
This bug seems to have existed since multicast support was added.

When an endpoint joins a multicast group, it adds the multicast address to the NIC's list of permanent addresses: https://github.com/google/gvisor/blob/b6ca96b9b9e71ba57653cf9d3ef0767771949378/pkg/tcpip/transport/udp/endpoint.go#L761-L763

However, when a multicast packet is delivered to the NIC, no per-endpoint filtering occurs: https://github.com/google/gvisor/blob/b6ca96b9b9e71ba57653cf9d3ef0767771949378/pkg/tcpip/stack/transport_demuxer.go#L166-L172

This has two disasterous implications:
1. any endpoint bound to a NIC that _has any endpoints which belong to a multicast group_ will receive those groups' traffic
1. any endpoint that sends outbound multicast traffic will also receive it, regardless of its membership and _regardless of the NIC's membership in the group_. this is due to the PacketLoop optimization: https://github.com/google/gvisor/blob/b6ca96b9b9e71ba57653cf9d3ef0767771949378/pkg/tcpip/network/ipv4/ipv4.go#L256-L260 which circumvents NIC address checking.

cc @iangudger in case you have a good solution. I was able to fix this with this bandaid patch:
```diff
diff --git a/pkg/tcpip/transport/udp/endpoint.go b/pkg/tcpip/transport/udp/endpoint.go
index 0a9d3c6c..f15d28e8 100644
--- a/pkg/tcpip/transport/udp/endpoint.go
+++ b/pkg/tcpip/transport/udp/endpoint.go
@@ -1403,6 +1403,20 @@ func (e *endpoint) HandlePacket(r *stack.Route, id stack.TransportEndpointID, pk
                return
        }
 
+       if header.IsV4MulticastAddress(id.LocalAddress) ||
+                       header.IsV6MulticastAddress(id.LocalAddress) {
+               var found bool
+               for _, mem := range e.multicastMemberships {
+                       if mem.multicastAddr == id.LocalAddress {
+                               found = true
+                               break
+                       }
+               }
+               if !found {
+                       return
+               }
+       }
+
        if !verifyChecksum(r, hdr, pkt) {
                // Checksum Error.
                e.stack.Stats().UDP.ChecksumErrors.Increment()
```
however I think a more appropriate fix is to avoid these endpoints in this call to `findAllEndpointsLocked`: https://github.com/google/gvisor/blob/b6ca96b9b9e71ba57653cf9d3ef0767771949378/pkg/tcpip/stack/transport_demuxer.go#L531

Discovered via https://bugs.chromium.org/p/chromium/issues/detail?id=1127298.

**Comment by ghanan94** [comment] 2020-09-17 05:36
This will be resolved by #3871 which will do IP packet filtering at the IP level instead of at the NIC.

**Comment by ghanan94** [comment] 2020-09-17 17:47
the behaviour of the transport_demuxer is expected since we want all multicast packets to be accepted by ALL-IP/wildcard address listeners (with matching ports). Note, normally this can be disabled with the `IP_MULTICAST_ALL` socket option (https://www.man7.org/linux/man-pages/man7/ip.7.html) but gvisor does not yet support that (#3977

**Comment by ghanan94** [comment] 2020-10-08 20:59
IP state refactor is done but we still need to move IP packet filtering to the network endpoints

**Comment by ghanan94** [comment] 2020-11-26 05:25
filters multicast (and unicast) packets at the network endpoint layer so this should be resolved now that the packet loop optimization does not bypass address checks 1a972411b36b8ad2543d3ea614c92e60ccbdffab

**Comment by ghanan94** [comment] 2020-11-30 22:40
Confirmed fixed, https://bugs.chromium.org/p/chromium/issues/detail?id=1127298 is resolved.

**Closed by ghanan94** 2020-11-30 22:40 UTC
Labels: area: networking, type: bug
