### ISSUE TITLE
Support for video devices

### ISSUE THREAD

**Issue by praganmat** [google/gvisor#7403] opened 2022-04-13 07:12 UTC
### Description

Hi,

Can we make the docker images for ffmpeg and opencv work with RUNSC?
For example, a Container application runningwith opencv, which can read camera stream, create e. g. 40 second videos based on an event detection, and then send these multiple videos to another Backend server?

Best Regards,
Prashant

### Is this feature related to a specific bug?

Not a bug. Enhancement to support video devices.

### Do you have a specific solution in mind?

All Camera based solutions with AI and IOT

**Comment by hbhasker** [comment] 2022-04-19 04:42
How does your opencv application access the camera? Most likely the issue with be mapping the device and getting opencv to recognize it which might require implementing a sort of driver for it in gVisor.

**Comment by praganmat** [comment] 2022-04-19 10:13
As far as i know, Opencv uses vrl2 - video4linux library to recognize it as a video device. I observed that video4linux package is not available in runsc enabled container applications. And the definitions of types of character devices is not available inside the container (/proc/devices file is missing.). Also system files (inside /proc/sys/dev) are also missing. Is there any way to enable these device definitions and mappings in runsc?

**Comment by fvoznika** [comment] 2022-04-19 18:09
I believe your requirements are covered in #7007 (there is also some details in #7286). Resolving as 
duplicate of #7007. Please re-open if this is different.

**Closed by fvoznika** 2022-04-19 18:09 UTC
Labels: type: enhancement
