### ISSUE TITLE
rust http server cannot listen on port

### ISSUE THREAD

**Issue by dgageot** [google/gvisor#75] opened 2018-06-18 13:38 UTC
I'm trying to run an http server written in Rust with this command:

```bash
docker run --init --runtime=runsc dgageot/rust
```

produces this error:
```bash
Starting web server v6
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ListenError { inner: Io(Os { code: 98, kind
: AddrInUse, message: "Address in use" }) }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
P9 server returned error. Gofer is shutting down. FD: 7, err: EOF
```

no matter which port I use.

Here's the code for the container:

```rust
extern crate shio;

use shio::prelude::*;
use shio::http::{Method};

fn hello_world(_: Context) -> Response {
    Response::with("Hello from rust\n")
}

fn main() {
    println!("Starting web server v6");

    Shio::default()
        .route((Method::GET, "/", hello_world))
        .run(":8080")
        .unwrap();
}
```

and the cargo descriptor:

```toml
[package]
name = "run"
version = "0.1.0"
authors = ["David Gageot <david@gageot.net>"]

[dependencies]
shio = "0.3.0"
```

it's built with this command to produce a statically linked binary.

```bash
cargo build --release --target x86_64-unknown-linux-musl
```

**Comment by iangudger** [comment] 2018-06-18 17:05
You app uses shio which depends on a socket option (SO_REUSEPORT) that we don't support:
https://github.com/mehcode/shio-rs/blob/master/lib/src/shio.rs#L87

Implementing SO_REUSEPORT is going to be difficult. Would it be possible for you to use a different library/framework?

**Comment by fvoznika** [comment] 2018-06-18 17:07
This was a regression added on Friday. Please check that d509d6c fixed it. Sorry for the trouble.

**Comment by dbcode** [comment] 2018-06-18 17:13
Fabricio, I don't think this bug is related to https://github.com/google/gvisor/commit/d509d6cd97f9af6cb7ce6081e55d8f1cfea44618

**Comment by fvoznika** [comment] 2018-06-18 17:21
I can repro it locally. I'll take a look...

**Comment by dgageot** [comment] 2018-06-18 18:30
@iangudger Thanks for the debugging!

I'm going to try a different library.
Of course, this is not something I want to be required to do :-)

**Comment by dgageot** [comment] 2018-06-18 18:35
FWIW, it works when I replace `shio` with `hyper`

**Comment by praveensastry** [comment] 2018-11-22 03:38
@fvoznika i would love to contribute to this, but i don't quite understand what could be the fix here. I have seen that it was mentioned above that "implementing SO_REUSEPORT would be difficult", so could you please guide me to identify a fix for this?

**Comment by avagin** [comment] 2018-11-22 03:55
@praveensastry I'm working on this right now.

**Comment by avagin** [comment] 2018-11-26 19:15
https://gvisor-review.googlesource.com/c/gvisor/+/11201

**Comment by HazCod** [comment] 2019-03-08 10:22
@avagin are there plans for merging your commits? I would really appreciate SO_REUSEPORT support since it e.g. helps nginx take on massive traffic loads.

**Comment by iangudger** [comment] 2019-03-08 18:56
It got merged as 652d068119052b0b3bc4a0808a4400a22380a30b. Please try it out!

**Comment by cedric05** [comment] 2019-04-11 02:29
this seems to be leftout. can i work on it?

**Comment by iangudger** [comment] 2019-04-11 02:37
The current status is we believe that we fixed the issue, but someone needs to verify that shio now works correctly in gVisor.

**Comment by cedric05** [comment] 2019-04-11 07:33
its working!!

**Comment by iangudger** [comment] 2019-04-11 13:28
Thanks for verifying! Closing this issue.

**Closed by iangudger** 2019-04-11 13:28 UTC
Labels: area: networking, bug, good first issue
