### ISSUE TITLE
Regression in recent version? error: setsockopt(..., IP_MTU_DISCOVER, IP_PMTUDISC_OMIT...) failed: Not supported

### ISSUE THREAD

**Issue by wryMitts** [google/gvisor#10760] opened 2024-08-13 07:51 UTC
### Description

On Gvisor versions between February & March 2024 from Debian repo, I used to be able to run Unbound. Now after a patch, Unbound crashes on startup with this error:

`error: setsockopt(..., IP_MTU_DISCOVER, IP_PMTUDISC_OMIT...) failed: Not supported`

I did see that path MTU is meant to be supported in a different issue. I also saw recent commits for MTU.  My Unbound version and code remains the same as I manually update my Dockerfiles & this container is untouched besides an update of the Gvisor binary itself.

Is this expected behavior? I can provide Dockerfile if needed.

### Steps to reproduce

Run Unbound from Alpine 3.19 in a new version of gVisor & a version of gVisor from earlier this year. 

### runsc version

```shell
runsc version release-20240807.0
spec: 1.1.0-rc.1
```

### docker version (if using docker)

```shell
Client: Docker Engine - Community
 Version:           27.1.1
 API version:       1.46
 Go version:        go1.21.12
 Git commit:        6312585
 Built:             Tue Jul 23 19:57:19 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.1.1
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.21.12
  Git commit:       cc13f95
  Built:            Tue Jul 23 19:57:19 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### uname

Linux 6.6.28 custom config, identical before & after issue

**Comment by milantracy** [comment] 2024-08-13 08:25
It will be helpful if you share the Dockerfile.

I hope I could reproduce it

**Comment by ayushr2** [comment] 2024-08-13 16:55
@kevinGC https://github.com/google/gvisor/commit/e367e0b134890cb8929f9a2bdb0c16710e70ffe8 looks relevant because of the changes in IP_MTU_DISCOVER. After that change, we don't support `IP_PMTUDISC_OMIT` value. Before that change, we would just return nil for IP_MTU_DISCOVER as a whole as it was not a supported option.

Although it was merged on May 15, so doesn't line up with mentioned timeline that the regression started between Feb and March runsc releases. @wryMitts could you double check on the runsc release bisection mentioned.

We need to handle `IP_PMTUDISC_OMIT` in https://github.com/google/gvisor/blob/63e04396fab47ef6cc076a641f45a7a9d77c6e4d/pkg/sentry/socket/netstack/netstack.go#L1774-L1796

and https://github.com/google/gvisor/blob/63e04396fab47ef6cc076a641f45a7a9d77c6e4d/pkg/sentry/socket/netstack/netstack.go#L2611-L2631

**Comment by kevinGC** [comment] 2024-08-14 20:36
I'll patch `IP_PMTUDISC_OMIT` in s.t. it works as it did previously, i.e. it just noops.

**Closed** 2024-08-15 17:35 UTC
Labels: type: bug

**Comment by kevinGC** [comment] 2024-08-15 18:00
This should be fixed. Please try it either with a new build or by building from source and reopen if it's still not working.
