### ISSUE TITLE
Catch log: "Container Sandbox: Unsupported syscall setsockopt" from Google Cloud Run

### ISSUE THREAD

**Issue by attakei** [google/gvisor#1739] opened 2020-02-03 14:15 UTC
I don't know if this is the correct site to publish this kind of issues as it is related to gVisor but on top of GKE.

## Description 

I try to use nginx-unit image ( https://hub.docker.com/r/nginx/unit ) on Google Cloud Run.
But, when running container, failed to call `kill` command.

### In container process

This image run entrypoint.sh and has has four steps in shell.

1. Run background process.
2. Inject configuration into process.
3. Stop backgroud process by `kill` comand.
4. Run foreground process.

Currently, when running application container based vendor official image, `kill` command is not accepted, service is not availaved.

Cloud Run has output this log in running container:

`
Container Sandbox: Unsupported syscall setsockopt(0xb,0x6,0x9,0x3ee1608589cc,0x4,0x29910fc86500). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/c/linux/amd64/setsockopt for more information.
`

## Reproduce steps

Build image from repository and run service from image.
https://gitlab.com/attakei-sandbox/gvisor-issue-setsockopt

I saw logs from service in Iowa region (GCP).
Please see [exported csv-log](https://gitlab.com/attakei-sandbox/gvisor-issue-setsockopt/blob/master/logs.csv) from GCP.

### Local docker engine

Run normally.

```
$ docker version                                                                                                      Client:
 Version:           19.03.5-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        633a0ea838
 Built:             Fri Nov 15 03:19:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.5-ce
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       633a0ea838
  Built:            Fri Nov 15 03:17:51 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.3.2.m
  GitCommit:        d50db0a42053864a270f648048f9a8b4f24eced3.m
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

### Local docker engine with runsc

Run normally.

```
$ runsc --version                                                                                                     runsc version release-20200127.0-51-g02997af5abd6
spec: 1.0.1-dev
```

```

```

**Comment by coronaction** [comment] 2020-05-15 05:15
Also getting similar message on Google Cloud Run for a container running a Java program wrapped in Quarkus framework. Happy to provide additional info if I know which one is of interest for this case. Just let me know

Some messages: 

1. Container Sandbox: Unsupported syscall setsockopt(0xae,0x0,0xb,0x3e6ff77fc1d4,0x4,0x0)
1. Container Sandbox: Unsupported syscall setsockopt(0xae,0x29,0x31,0x3e6ff77fd7b4,0x4,0x4)
1. Container Sandbox: Unsupported syscall setsockopt(0xae,0x29,0x12,0x3e6ff77fd7bc,0x4,0x4)
1.

**Comment by pebo** [comment] 2020-05-29 13:36
The lastest official Node version v12.17.0 triggers setsockopt warnings on Cloud Run, e.g.

````
Container Sandbox: Unsupported syscall setsockopt(0x13,0x6,0x6,0x3ea340cbc70c,0x4,0x1cc3929404b1).
Container Sandbox: Unsupported syscall setsockopt(0x1b,0x6,0x6,0x3ea340cbc70c,0x4,0x1cc3929404b1)
````

Would it be possible to suppress these warning as cloud logging gets spammed?

**Comment by didier-durand** [comment] 2020-05-29 13:40
To whom are you asking this question: to gVisor team or to me?

**Comment by pebo** [comment] 2020-05-29 13:46
@didier-durand You probably got notified as you've subscribe to this issue. 

I guess it's a feature request to the gVisor team - It would be nice to be able to suppress warnings (e.g. for socket options that is / cannot be implemented i gVisor).

**Comment by didier-durand** [comment] 2020-05-29 13:52
I agree with you but then we have to be able to select this option from the Google Cloud UI if we need to remove this logging.

**Comment by fevernova90** [comment] 2020-06-23 14:20
Same for me, getting this syslog spamming my whole Logging Stack. Running Cloud Run.

**Comment by Sytten** [comment] 2020-06-24 22:01
Also having this issue, but different code:
```
Container Sandbox: Unsupported syscall setsockopt(0x13,0x6,0x6,0x3ef9e6878e2c,0x4,0xab9dd404b1)
```
I am using nodejs 12.18.

**Comment by dylanjt** [comment] 2020-06-29 01:01
I am also seeing this error. For me, I _think_ it is originating from the Hyper library (Hyper is the Rust community's goto HTTP server/client). It seems to trigger anytime my code attempts an outbound HTTP request (which fails). Still digging in, might have more info later, but this is definitely having impact / not insignificant in my case.

**Comment by shvgn** [comment] 2020-07-05 23:03
I use k6.io to run load tests on my service in Cloud Run. What I see it that roughly 2% of tcp connections fail. In Cloud Run logs I see lots of these (along with membarrier):

```
Container Sandbox: Unsupported syscall setsockopt(0x17,0x6,0x6,0x3e6f301f9734,0x4,0x0). It is very likely that you can safely ignore this ...
```

k6 warnings during the test run:

```
...
WARN[0629] Request Failed      error="Get \"https://<...>.run.app/<...>\": dial tcp <...>:443: i/o timeout"
WARN[0629] Request Failed      error="Get \"https://<...>.run.app/<...>\": unexpected EOF"
WARN[0629] Request Failed      error="Post \"https://<...>.run.app/<...>\": dial tcp <...>:443: i/o timeout"
WARN[0630] Request Failed      error="Get \"https://<...>.run.app/<...>\": unexpected EOF"
WARN[0630] Request Failed      error="Post \"https://<...>.run.app/<...>\": write tcp <...>:62719-><...>:443: write: broken pipe"
WARN[0631] Request Failed      error="Post \"https://<...>.run.app/<...>\": dial tcp <...>:443: i/o timeout"
WARN[0631] Request Failed      error="Post \"https://<...>.run.app/<...>\": dial tcp <...>:443: i/o timeout"
WARN[0632] Request Failed      error="Post \"https://<...>.run.app/<...>\": dial tcp <...>:443: i/o timeout"
WARN[0632] Request Failed      error="Post \"https://<...>.run.app/<...>\": unexpected EOF"
WARN[0632] Request Failed      error="Post \"https://<...>.run.app/<...>\": unexpected EOF"
WARN[0633] Request Failed      error="Post \"https://<...>.run.app/<...>\": unexpected EOF"
WARN[0633] Request Failed      error="Get \"https://<...>.run.app/<...>\": dial tcp <...>:443: i/o timeout"
WARN[0633] Request Failed      error="Get \"https://<...>.run.app/<...>\": dial tcp <...>:443: i/o timeout"
WARN[0633] Request Failed      error="Post \"https://<...>.run.app/<...>\": dial tcp <...>:443: i/o timeout"
WARN[0634] Request Failed      error="Post \"https://<...>.run.app/<...>\": dial tcp <...>:443: i/o timeout"
WARN[0634] Request Failed      error="Post \"https://<...>.run.app/<...>\": EOF"
```

The service base image is node:14-alpine.

**Comment by iangudger** [comment] 2020-07-06 02:20
This seems to be SOL_TCP, TCP_KEEPCNT which was fixed in 4b9652d.

**Comment by RtypeStudios** [comment] 2020-07-13 13:11
I have thousands of these appearing. I'm using .net core on this image:

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.2-alpine3.11

Would be great to filter these out make log reading a bit difficult.

![image](https://user-images.githubusercontent.com/990114/87308005-29a42b80-c54d-11ea-9445-86fbdd7fea58.png)

**Comment by AndreiIgna** [comment] 2020-08-11 18:16
@iangudger is there something we can do after that fix?

Having the same problem, it's quite hard to see something useful in logs when this line is duplicated so many times
<img width="1277" alt="Screenshot 2020-08-11 at 20 13 59" src="https://user-images.githubusercontent.com/263021/89933405-4ea0c280-dc0f-11ea-90a9-cad87969e07b.png">

gVisor is referenced in the log https://gvisor.dev/c/linux/amd64/setsockopt

**Comment by ytnobody** [comment] 2020-08-14 03:20
I saw too. Today `Container Sandbox: Unsupported syscall membarrier` log on Google Cloud Run.

![スクリーンショット 2020-08-14 12 08 20](https://user-images.githubusercontent.com/278841/90209958-b6c9f100-de27-11ea-934e-2635efc8aea5.png)

Frequency of this phenomenon is about 1 to 5 times on a day.

**Comment by iangudger** [comment] 2020-08-14 12:11
@RtypeStudios Can you post the full log line? You cut off the important part.

@AndreiIgna Your logs are about a different socket option (SOL_IP, IP_MTU_DISCOVER). That is tracked in #1643.

@ytnobody Your logs are about a different syscall entirely (membarrier). Please see the compatibility note in the log line that you posted. membarrier is being tracked in #267.

@nlacasse Has 4b9652d rolled out to Cloud Run yet?

**Comment by pebo** [comment] 2020-09-30 21:05
We get "warnings" logged for Cloud Run containers running a JVM app with ktor / netty and google libraries for accessing BQ and GCS.

Is there an issue tracking: `Container Sandbox: Unsupported syscall setsockopt(0x13,0x0,0xb,0x3ed13c7f9974,0x4,0x2c1)` ?

**Comment by knyttl** [comment] 2020-11-20 21:28
Similar thing here: spamming my logs, hard to see whatt is relevant.

**Comment by marcelsauer4711** [comment] 2020-11-23 13:25
getting the same message in the logs. Java Spring Application....

`{
    "textPayload": "Container Sandbox: Unsupported syscall setsockopt(0xc9,0x29,0x12,0x3dfefc9fd864,0x4,0x3). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/c/linux/amd64/setsockopt for more information.",
    "insertId": "5fbbb75400091587f1e993e7",
    "resource": {
      "type": "cloud_run_revision",
      "labels": {
        "revision_name": "helloworld-24fjz",
        "project_id": "xxx",
        "configuration_name": "helloworld",
        "location": "europe-west1",
        "service_name": "helloworld"
      }
    },
    "timestamp": "2020-11-23T13:21:24.595316477Z",
    "severity": "DEBUG",
    "labels": {
      "instanceId": "xxx"
    },
    "logName": "xxx",
    "receiveTimestamp": "2020-11-23T13:21:24.783347593Z"
  }`

**Comment by sshcherbakov** [comment] 2021-01-28 18:22
Here's an error from my Java Spring Boot based gRPC server on Cloud Run:
```
Container Sandbox: Unsupported syscall setsockopt(0x6,0x29,0x31,0x3efbd9dfc3a4,0x4,0x0). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/c/linux/amd64/setsockopt for more information
```

**Comment by RtypeStudios** [comment] 2021-02-03 10:51
@iangudger So sorry, just saw your request for more information. I'm still getting thousands of them.

2021-02-03 18:09:04.374 AWSTContainer Sandbox: Unsupported syscall setsockopt(0x12e,0x1,0xd,0x3e23363fefb8,0x8,0x3e234cef5490). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/c/linux/amd64/setsockopt for more information.

2021-02-03 18:09:04.375 AWSTContainer Sandbox: Unsupported syscall setsockopt(0x12e,0x1,0xd,0x3e23363fefb8,0x8,0x3e234cf1a688). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/c/linux/amd64/setsockopt for more information.

2021-02-03 18:09:05.489 AWSTContainer Sandbox: Unsupported syscall setsockopt(0x12f,0x1,0xd,0x3e2345fffa38,0x8,0x0). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/c/linux/amd64/setsockopt for more information.

**Comment by sshcherbakov** [comment] 2021-02-03 21:09
0xd and 0x31 have only first bit (SO_DEBUG) in common.
Am I completely off here.

**Comment by RtypeStudios** [comment] 2021-02-04 05:54
seems the say in the errors I have posted, but different to the errors others have posted. I have no idea what they mean :)

**Comment by sshcherbakov** [comment] 2021-02-08 17:53
Sorry, the error I listed didn't influence the functionality of my gRPC server (the reason of the malfunction was something else), please ignore.

**Comment by louis030195** [comment] 2021-12-07 14:46
I don't know if I should create a new issue:

>Container Sandbox: Unsupported syscall sched_getattr(0x37d,0x3e045912c300,0x38,0x0,0x1,0x3e045912c300). It is very likely that you can safely ignore this message and that this is not the cause of any error you might be troubleshooting. Please, refer to https://gvisor.dev/docs/user_guide/compatibility/linux/amd64/sched_getattr for more information.

The documentation page does not exist.
I suspect to be caused by the use of [playwright.dev](https://playwright.dev/) (python API) or maybe beautifulsoup

```dockerfile
FROM mcr.microsoft.com/playwright:focal
```

dependencies

```requirements.txt
google-cloud
google-cloud-firestore
google-cloud-storage
Flask[async]==2.0.2
gunicorn==20.1.0
beautifulsoup4
playwright
requests
fire
tqdm
pandas
openai
scraperapi-sdk
parsel
aiologger
```

**Comment by johnf1004** [comment] 2022-05-25 22:21
Did anyone ever figure out how to suppress these warning messages?

**Comment by petehannam** [comment] 2022-05-26 04:19
@johnf1004 use the gen2 execution environment: https://cloud.google.com/run/docs/about-execution-environments

**Comment by johnf1004** [comment] 2022-05-30 23:04
Nice, thank you @petehannam !

Works nicely when deploying through the console - any idea if it's possible to specify the gen2 environment with gcloud? Looking through the flags for `gcloud run deploy` and cant see anything

**Comment by petehannam** [comment] 2022-05-30 23:45
@johnf1004 The [documentation](https://cloud.google.com/run/docs/configuring/execution-environments#command-line) has details on how to run it via the command line:

`gcloud beta run deploy --image IMAGE_URL --execution-environment gen2`

**Comment by knyttl** [comment] 2022-05-31 05:09
Note that I am avoiding `gen2` because of slower cold starts.

**Comment by kevinGC** [comment] 2022-06-10 17:58
This issue sort of straddles the line between gVisor and its downstream consumers. I believe that Cloud Run and others allow for logs to be filtered via terms such as `NOT "Unsupported syscall setsockopt"`.

From gVisor's perspective, the unsupported syscall logs are important. In the rare cases where unsupported syscalls do affect program behavior, the logs are an important debugging tool. We don't want to remove them, as when things do break they will be extra difficult to debug both for users and for us.

Please do file specific issues if you're getting major logspam or application behavior is affected. For now, this issue seems to have become a catchall and I think we should have users file specific bugs for specific messages.

**Comment by kevinGC** [comment] 2022-06-10 17:59
For anyone coming across this in the future: if you're seeing the `Unsupported syscall` message and it either is (1) affecting application behavior or (2) logspamming like crazy, please open an issue for your particular message. I'm closing this one because it's too many issues clumped together and it's not clear which need addressing.

**Closed by kevinGC** 2022-06-10 17:58 UTC
Labels: type: bug, area: compatibility, priority: p2, area: Cloud Run
