### ISSUE TITLE
gRPC unable to reach another container in Kubernetes

### ISSUE THREAD

**Issue by fvoznika** [google/gvisor#807] opened 2019-09-04 16:49 UTC
From @sdeoras:
Hi Folks, I am trying out gvisor on GKE and see that pods on two different nodes (in gvisor node pool) can't communicate with each other over ClusterIP. Is this expected behavior on GKE or a limitation of gvisor? I have been able to get pods to communicate running in gVisor on other cluster (GCE VM's) that was brought up manually using kubeadm. Thanks.

Here is a quick doc outlining steps to repro the issue:
https://gist.github.com/sdeoras/42542c1911a93e8d696f9ddad94887e6

The error is:
`rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: i/o timeout"`

**Comment by fvoznika** [comment] 2019-09-04 16:53
It works with an old cluster of mine. I'll try again using the same configuration as yours to see if it repros.

```
> kubectl logs pod/ping-pong-gvisor-job-5c592
client:    0, pong
client:   -1, ping
client:   -2, pong
client:   -3, ping
client:   -4, pong
client:   -5, ping
client:   -6, pong
client:   -7, ping
client:   -8, pong
client:   -9, ping
...
```

**Comment by fvoznika** [comment] 2019-09-04 18:21
It also worked. I had to break the command you pasted into 2 to make it work. One to create the cluster with a regular default node pool and added an additional node pool for gVisor, but apart from that, all the options I used were the same.

```
> kubectl logs pod/ping-pong-gvisor-job-khrkn
client:    0, pong
client:   -1, ping
client:   -2, pong
```
```
> gcloud container node-pools list --cluster=sandboxed
NAME          MACHINE_TYPE   DISK_SIZE_GB  NODE_VERSION
default-pool  n1-standard-2  25            1.13.7-gke.24
gvisor-pool   n1-standard-2  25            1.13.7-gke.24

> kubectl get  nodes
NAME                                       STATUS   ROLES    AGE   VERSION
gke-sandboxed-default-pool-5b9cfd81-2043   Ready    <none>   56m   v1.13.7-gke.24
gke-sandboxed-default-pool-5b9cfd81-cgxw   Ready    <none>   56m   v1.13.7-gke.24
gke-sandboxed-default-pool-5b9cfd81-prk6   Ready    <none>   56m   v1.13.7-gke.24
gke-sandboxed-gvisor-pool-35f2236e-29l8    Ready    <none>   51m   v1.13.7-gke.24
gke-sandboxed-gvisor-pool-35f2236e-crnh    Ready    <none>   51m   v1.13.7-gke.24
gke-sandboxed-gvisor-pool-35f2236e-wtll    Ready    <none>   51m   v1.13.7-gke.24
```
Both client and server are running with gVisor:
```
> kubectl describe pod/ping-pong-gvisor-job-khrkn | grep Node:
Node:           gke-sandboxed-gvisor-pool-35f2236e-wtll/10.128.15.209
> kubectl describe pod/ping-pong-gvisor-server-deployment-6dd7c668d-xxgwq | grep Node:
Node:           gke-sandboxed-gvisor-pool-35f2236e-crnh/10.128.15.210
```

**Comment by sdeoras** [comment] 2019-09-04 18:26
@fvoznika thanks so much. Let me try with both the default and the gvisor node pools active together.

**Comment by sdeoras** [comment] 2019-09-04 21:33
@fvoznika it worked for me when I had both the default pool and gvisor pool in the cluster. So looks like the issue is when user deletes the default pool and only keeps the gvisor pool in the cluster, networking is not fully functional. I recreated that scenario and see not pods are up and it is clear why networking was not functional.

Please feel free to close the issue. I'll make sure I have default pool enabled.

```
kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                         READY   STATUS    RESTARTS   AGE    IP              NODE                              NOMINATED NODE   READINESS GATES
kube-system   event-exporter-v0.2.4-5f88c66fb7-d976h       0/2     Pending   0          110s   <none>          <none>                            <none>           <none>
kube-system   fluentd-gcp-scaler-59b7b75cd7-l4scn          0/1     Pending   0          99s    <none>          <none>                            <none>           <none>
kube-system   fluentd-gcp-v3.2.0-4f2fp                     2/2     Running   0          96s    10.138.15.197   gke-gvisor-gvisor-991debe5-fvkg   <none>           <none>
kube-system   fluentd-gcp-v3.2.0-b28bd                     2/2     Running   0          95s    10.138.15.195   gke-gvisor-gvisor-991debe5-lfp5   <none>           <none>
kube-system   fluentd-gcp-v3.2.0-psx9b                     2/2     Running   0          94s    10.138.15.196   gke-gvisor-gvisor-991debe5-9bnh   <none>           <none>
kube-system   heapster-v1.6.1-77c8874fcc-w4tcf             0/3     Pending   0          109s   <none>          <none>                            <none>           <none>
kube-system   kube-dns-6987857fdb-cl779                    0/4     Pending   0          110s   <none>          <none>                            <none>           <none>
kube-system   kube-dns-autoscaler-bb58c6784-zgx2k          0/1     Pending   0          99s    <none>          <none>                            <none>           <none>
kube-system   kube-proxy-gke-gvisor-gvisor-991debe5-9bnh   1/1     Running   0          95s    10.138.15.196   gke-gvisor-gvisor-991debe5-9bnh   <none>           <none>
kube-system   kube-proxy-gke-gvisor-gvisor-991debe5-fvkg   1/1     Running   0          96s    10.138.15.197   gke-gvisor-gvisor-991debe5-fvkg   <none>           <none>
kube-system   kube-proxy-gke-gvisor-gvisor-991debe5-lfp5   1/1     Running   0          94s    10.138.15.195   gke-gvisor-gvisor-991debe5-lfp5   <none>           <none>
kube-system   l7-default-backend-fd59995cd-8ss65           0/1     Pending   0          110s   <none>          <none>                            <none>           <none>
kube-system   metrics-server-v0.3.1-c4cddd5f5-xdc4f        0/2     Pending   0          106s   <none>          <none>                            <none>           <none>
```

kubectl describe on one of them indicates that pod spec did not have tolerations for node taints

`kubectl describe -n kube-system pods/kube-dns-6987857fdb-cl779`

```
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  2m4s (x5 over 2m8s)  default-scheduler  no nodes available to schedule pods
  Warning  FailedScheduling  114s (x4 over 115s)  default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  113s (x2 over 113s)  default-scheduler  0/2 nodes are available: 2 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  28s (x11 over 113s)  default-scheduler  0/3 nodes are available: 3 node(s) had taints that the pod didn't tolerate.
```

**Closed** 2019-09-05 21:50 UTC
Labels: area: networking, bug
