### ISSUE TITLE
E: Setting TIOCSCTTY for slave fd 11 failed!

### ISSUE THREAD

**Issue by fvoznika** [google/gvisor#796] opened 2019-08-31 00:39 UTC
`apt-get install` any package. Midway through it, the `setting TIOCSCTTY failed` message shows up and the output gets misaligned from then on.

Repro:
```shell
docker run --rm --runtime=runsc -ti debian bash -c "apt-get update && apt-get install less"
```

```
Get:1 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
...
Selecting previously unselected package less.
(Reading database ... 6499 files and directories currently installed.)
Preparing to unpack .../less_481-2.1_amd64.deb ...
Unpacking less (481-2.1) ...
E: Setting TIOCSCTTY for slave fd 11 failed! - ioctl (1: Operation not permitted)
                                                                                 Setting up less (481-2.1) ...
                                                                                                              debconf: unable to initialize frontend: Dialog
                                    debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
                                                                       debconf: falling back to frontend: Readline
                                                                                                                  debconf: unable to initialize frontend: Readline
                                          debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
                                                                                                                 debconf: falling back to frontend: Teletype
```

**Comment by kevinGC** [comment] 2020-06-22 18:52
Duplicate of #3045  (that bug is newer, but the relevant explanation and context is there).

**Closed by kevinGC** 2020-06-22 18:52 UTC
Labels: area: tty, type: bug

**Comment by nlacasse** [comment] 2023-11-07 17:37
Should be fixed by https://github.com/google/gvisor/pull/9647
