### ISSUE TITLE
gvisor.dev/gvisor/runsc/cmd doesn't compile on go branch

### ISSUE THREAD

**Issue by iangudger** [google/gvisor#3130] opened 2020-07-01 23:19 UTC
```
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20200701225027-60fa47d34063/runsc/cmd/help.go:67:90: h.cdr.Name undefined (type *subcommands.Commander has no field or method Name)
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20200701225027-60fa47d34063/runsc/cmd/help.go:73:9: h.cdr.Name undefined (type *subcommands.Commander has no field or method Name)
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20200701225027-60fa47d34063/runsc/cmd/help.go:74:8: h.cdr.VisitGroups undefined (type *subcommands.Commander has no field or method VisitGroups)
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20200701225027-60fa47d34063/runsc/cmd/help.go:74:29: undefined: subcommands.CommandGroup
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20200701225027-60fa47d34063/runsc/cmd/help.go:75:9: h.cdr.ExplainGroup undefined (type *subcommands.Commander has no field or method ExplainGroup)
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20200701225027-60fa47d34063/runsc/cmd/help.go:78:112: h.cdr.Name undefined (type *subcommands.Commander has no field or method Name)
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20200701225027-60fa47d34063/runsc/cmd/help.go:82:88: h.cdr.Name undefined (type *subcommands.Commander has no field or method Name)
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20200701225027-60fa47d34063/runsc/cmd/help.go:87:8: h.cdr.VisitCommands undefined (type *subcommands.Commander has no field or method VisitCommands)
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20200701225027-60fa47d34063/runsc/cmd/help.go:87:31: undefined: subcommands.CommandGroup
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20200701225027-60fa47d34063/runsc/cmd/help.go:89:10: h.cdr.ExplainCommand undefined (type *subcommands.Commander has no field or method ExplainCommand)
../../../go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20200701225027-60fa47d34063/runsc/cmd/help.go:89:10: too many errors
```

**Comment by ianlewis** [comment] 2020-07-06 01:35
This looks to be caused by the go branch using an old version of the subcommands package. It was updated in https://github.com/google/gvisor/commit/74e397e39accbeb9fcb5382ce963df55014ae7ce but I suppose the go branch is using the old version for some reason?

**Comment by prattmic** [comment] 2020-07-07 19:10
It works for me:

```
$ git checkout go
$ go build -o exe gvisor.dev/gvisor/runsc
$ ./exe
Usage: exe <flags> <subcommand> <subcommand args>
...
```

Perhaps you need to convince Go to download the latest versions required by go.mod? I can't recall the rules w.r.t. versioning there.

**Comment by ianlewis** [comment] 2020-07-08 06:52
go build should download and use the right versions. It also worked for me on a fresh GOPATH

```
$ go build -o exe gvisor.dev/gvisor/runsc
go: downloading github.com/google/subcommands v0.0.0-20190508160503-636abe8753b8
go: downloading github.com/golang/protobuf v1.3.1
go: downloading github.com/syndtr/gocapability v0.0.0-20180916011248-d98352740cb2
go: downloading golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: downloading github.com/opencontainers/runtime-spec v0.1.2-0.20171211145439-b2d941ef6a78
go: downloading github.com/gofrs/flock v0.6.1-0.20180915234121-886344bea079
go: downloading github.com/google/btree v1.0.0
go: finding module for package golang.org/x/time/rate
go: downloading github.com/vishvananda/netlink v1.0.1-0.20190318003149-adb577d4a45e
go: downloading github.com/cenkalti/backoff v0.0.0-20190506075156-2146c9339422
go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
go: downloading github.com/kr/pty v1.1.1
go: downloading github.com/vishvananda/netns v0.0.0-20171111001504-be1fbeda1936
go: found golang.org/x/time/rate in golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e

$ ./exe --version
runsc version VERSION_MISSING
spec: 1.0.1-dev
```

I'll close this a WAI but feel free to re-open if you find out more about why it was failing.

**Closed by ianlewis** 2020-07-08 06:52 UTC
Labels: area: tooling, type: bug
