### ISSUE TITLE
Docker volume & bind mount support after VFS2 & LISAFS

### ISSUE THREAD

**Issue by Waldenesque** [google/gvisor#9140] opened 2023-07-04 00:26 UTC
### Description

I'm looking into gVisor and hope to clarify what works with Docker. It sounds like only volumes worked before, but now bind mounts also work with VFS2 & LISAFS? I wasn't clear searching GitHub or Google Groups.

Using Docker volumes and bind mounts, are regular files and folders expected to work identically between runsc and runc? Do special or device files and folders present any common problems?

I'm not looking for guarantees nor a laundry list. I'm just asking about typical expectations using gVisor as of 2023.

Thank you.

**Comment by EtiennePerot** [comment] 2023-07-05 18:51
In today's gVisor, in conjunction with Docker, with LISAFS+VFS2 enabled, AFAIK:

- Volumes work.
- Regular files and directories work.
- Some bind mounts work but not all flags are supported; look for the string "bind" in [this test](https://github.com/google/gvisor/blob/master/test/syscalls/linux/mount.cc) to verify. Notably, gVisor currently doesn't support `MS_REC` or `MS_SLAVE`.
- Device files do not _generically_ work, but NVIDIA GPU devices are starting to be supported.
- FIFOs and UDS files are supported but need a flag change to allow them through to the host (`--host-fifo` and `--host-uds` respectively).

I am closing this issue as this is not a bug report. For further non-issue-related questions, please use the [gvisor-users mailing list](https://groups.google.com/g/gvisor-users).

**Closed by EtiennePerot** 2023-07-05 18:51 UTC
Labels: type: enhancement

**Comment by Waldenesque** [comment] 2023-07-05 21:10
Sorry for the wrong post, but thanks so much for your answer. That's what I was hoping for, just a general overview.

Thank you!
