### ISSUE TITLE
OOMs are not mapped through containerd -> kubernetes properly

### ISSUE THREAD

**Issue by amscanne** [google/gvisor#2433] opened 2020-04-13 16:22 UTC
Forked from #1967 (see comment there).

Apparently an OOM running a standard runc container maps to an OOMKilled status in Kubernetes, but this does not work properly for runsc containers. Needs investigation.

**Comment by ianlewis** [comment] 2020-04-15 00:37
Original comment from @turkenh on #1967 

----

I guess we just hit this issue. We are running gke gvisor enabled and one of our containers keeps crashing only with the following info in `describe` output:

```
    Last State:     Terminated
      Reason:       Error
      Exit Code:    128
      Started:      Mon, 13 Apr 2020 13:48:51 +0300
      Finished:     Mon, 13 Apr 2020 13:52:36 +0300

  Normal   SandboxChanged  30s                  kubelet, gke-sandboxed-worklo-c55afeb1-p6b0  Pod sandbox changed, it will be killed and re-created.
```

Even we have stackdriver logging enabled, we could not find anything valuable other than `ContainerDied` event logs. Neither kubelet nor container runtime does not provide anything valuable. Even further, GCP console does not show resource usage for gvisor enabled workloads.

We could only identify the root cause by ssh'ing to node and checking kernel logs with `dmesg`.  

```
[216849.759079] Task in /kubepods/burstable/pode81fb814-df6b-4428-8d58-68a005dd4f43/5d5b52d847279a1062e529baeb56789b99c9ce19bd133f4a95ac78787a2cb27b killed as a result of limit of /kubepods/burstable/pode81fb814-df6b-4428-8d58-68a005dd4f43
[216849.780174] memory: usage 524288kB, limit 524288kB, failcnt 359
[216849.786341] memory+swap: usage 524288kB, limit 9007199254740988kB, failcnt 0
[216849.793663] kmem: usage 7772kB, limit 9007199254740988kB, failcnt 0
[216849.800168] Memory cgroup stats for /kubepods/burstable/pode81fb814-df6b-4428-8d58-68a005dd4f43: cache:0KB rss:0KB rss_huge:0KB shmem:0KB mapped_file:0KB dirty:0KB writeback:0KB swap:0KB inactive_anon:0KB active_anon:0KB inactive_file:0KB active_file:0KB unevictable:0KB
[216849.824338] Memory cgroup stats for /kubepods/burstable/pode81fb814-df6b-4428-8d58-68a005dd4f43/5d5b52d847279a1062e529baeb56789b99c9ce19bd133f4a95ac78787a2cb27b: cache:495272KB rss:21128KB rss_huge:0KB shmem:495308KB mapped_file:475200KB dirty:0KB writeback:0KB swap:0KB inactive_anon:318300KB active_anon:198216KB inactive_file:0KB active_file:0KB unevictable:0KB
[216849.856854] Tasks state (memory values in pages):
[216849.862125] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[216849.871111] [4010236]     0 4010236    31311     3478   110592        0          -998 exe
[216849.879532] [4010240] 65534 4010240   197816    22827   851968        0           992 exe
[216849.887981] [4010330]     0 4010330    41139     3592   208896        0           992 exe
[216849.896420] Memory cgroup out of memory: Kill process 4010240 (exe) score 1167 or sacrifice child
[216849.905716] Killed process 4010240 (exe) total-vm:791264kB, anon-rss:14528kB, file-rss:16988kB, shmem-rss:59792kB
[216849.918096] oom_reaper: reaped process 4010240 (exe), now anon-rss:0kB, file-rss:0kB, shmem-rss:59792kB
```

This was a very painful process and we lost quite some time while debugging. If we could see `OOM Killed` at Kubernetes level (just like we see without gvisor), issue would be solved in minutes compared to days.

**Comment by ianlewis** [comment] 2020-04-16 03:05
I've managed to reproduce this.

This is a Pod that generally reproduces the problem. If you remove the runtimeClassName you get OOMKilled as the reason.
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: memtest
  name: memtest
  namespace: default
spec:
  runtimeClassName: gvisor
  containers:
  - name: memtest
    image: ubuntu
    command: ["perl", "-wE", "my @xs; for (1..2**20) { push @xs, q{a} x 2**20 }; say scalar @xs;"]
    resources:
      limits:
        memory: 100Mi
```

It looks like the problem comes down to gvisor-containerd-shim not forwarding oom score notifications. It looks like runc's shim takes care of it but runsc's shim doesn't. Comments indicate it's relying on `runsc events` for oom notifications but `runsc events` doesn't track OOM events. I think gvisor-containerd-shim should just use the cgroup's oom notifications just like runc's shim but still investigating...

**Comment by ianlewis** [comment] 2020-04-21 06:12
This isn't an issue in gVisor but rather the containerd shim. I'm going to close the issue here but you can track at https://github.com/google/gvisor-containerd-shim/issues/56

**Closed by ianlewis** 2020-04-21 06:12 UTC
Labels: area: stability, priority: p1, type: bug
