### ISSUE TITLE
DNS not working in Docker Compose

### ISSUE THREAD

**Issue by boostpaal** [google/gvisor#115] opened 2018-11-20 17:18 UTC
DNS lookups fail in Docker Compose 2.3.

*docker-compose.yml*

```yaml
version: '2.3'
services:
  gvisor_test:
    command: node /home/test.js
    image: node:8-alpine
    runtime: runsc
    volumes:
      - /home/ubuntu/compose/test.js:/home/test.js
```

*test.js*

```javascript
const http = require('http')
http.get('http://www.google.com', res => console.log(res))
```

Error:
```bash
$ docker-compose up
Starting compose_gvisor_test_1 ... done
Attaching to compose_gvisor_test_1
gvisor_test_1  | events.js:183
gvisor_test_1  |       throw er; // Unhandled 'error' event
gvisor_test_1  |       ^
gvisor_test_1  | 
gvisor_test_1  | Error: getaddrinfo EAI_AGAIN www.google.com:80
gvisor_test_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
compose_gvisor_test_1 exited with code 1
```

```bash
$ uname -a
Linux ubuntu-2 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
$ docker version
Client:
Version:           18.09.0
API version:       1.39
Go version:        go1.10.4
Git commit:        4d60db4
Built:             Wed Nov  7 00:48:57 2018
OS/Arch:           linux/amd64
Experimental:      false

Server: Docker Engine - Community
Engine:
 Version:          18.09.0
 API version:      1.39 (minimum version 1.12)
 Go version:       go1.10.4
 Git commit:       4d60db4
 Built:            Wed Nov  7 00:16:44 2018
 OS/Arch:          linux/amd64
 Experimental:     false
```

I've tried using the `use-vc` and other resolve options in Compose (http://man7.org/linux/man-pages/man5/resolv.conf.5.html)  to force TCP over UDP, with no luck:

```yaml
version: '2.3'
services:
  gvisor_test:
    command: node /home/test.js
    image: node:8-alpine
    runtime: runsc
    volumes:
      - /home/ubuntu/compose/test.js:/home/test.js
    dns_opt:
      - use-vc
```

**Comment by boostpaal** [comment] 2018-11-20 18:54
Needs more testing.

**Comment by iangudger** [comment] 2018-12-02 05:16
It appears that you are trying to connect to a DNS server on 127.0.0.11:53, but that there isn't a DNS server in the sandbox running on that port. When it comes to networking, the sandbox behaves like a VM. localhost is the sandbox's localhost. You might be able to talk to the DNS server on the host by using the host's IP address.

Another thing you can try is [enabling network passthrough](https://github.com/google/gvisor#enabling-network-passthrough). This makes networking behave more like a normal container at the cost of security. I am not sure if this will help as I think the sandbox runs in a network namespace with its own loopback on the host.

**Comment by boostpaal** [comment] 2018-12-03 10:43
Network passthrough works but it's not a viable option for security reasons. I seems like Compose's native DNS server is the root of the problem. There might be a missing DNS feature that gVisor requires. I think submitting an issue to Compose would be the right way to go from here.

**Comment by boostpaal** [comment] 2018-12-03 12:55
We have resolved the issue. We tried to change the DNS server in Compose by: 
```yaml
version: '2.3'
services:
  apiconbug:
    restart: always
    image: apiconbug
    tty: true
    working_dir: /home/alpine/apiconbug
    runtime: runsc
    dns:
        - 8.8.8.8
```
However, `resolv.conf` inside the container would still be:
```
nameserver 127.0.0.11
```
which would render the same problem.

When you look at the networks created by Compose, we see:
```bash
$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
c9fcf0c8d7dc        bridge              bridge              local
29cf0bbb8e49        nodebug_default     bridge              local
```

The `nodebug_default` network is created by Compose when it has `runsc` as runtime,  The Options object is empty:
```javascript
$ docker network inspect 29cf0bbb8e49
[
    {
        "Name": "apiconbug_default",
        "Id": "a3fcbc8dbf8c8500ff9eee3f4ca7328f7b1dd181ad601168ccbe48be4fee99ac",
        "Created": "2018-11-30T09:50:39.643998227+01:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {},
        "Options": {},  // <--- EMPTY
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "apiconbug",
            "com.docker.compose.version": "1.22.0"
        }
    }
]
```

The **bridge** network has these Options:
```
$ docker network inspect c9fcf0c8d7dc
[
    {
        "Name": "bridge",
        ...
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        ...
    }
]
```

We then switched to using the bridge network:
```yaml
version: '2.3'
services:
  apiconbug:
    restart: always
    image: apiconbug
    tty: true
    working_dir: /home/alpine/apiconbug
    runtime: runsc
    dns:
        - 8.8.8.8
    network_mode: "bridge"
```

and voila, `resolv.conf`:
```
nameserver 8.8.8.8
```

DNS lookups are now OK.

Would be nice to know which of these options resolve the problem, what the problem actually is, and how to configure these options in Compose.

I think this is no longer a gVisor issue, so I can close it unless you have more to add @iangudger.

**Comment by Anjali05** [comment] 2019-05-17 00:09
I am getting error in apt update inside the ubuntu image when I run it with gvisor, with runc it work fine. Can someone tell me how to fix it?
content of the conf file inside the container:

root@d846d6c54be4:/# cat  /etc/resolv.conf 
search utah.cloudlab.us
nameserver 10.0.0.2
nameserver 8.8.8.8


error:
root@d846d6c54be4:/# apt update
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease                  
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu bionic-security InRelease        
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease          
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists... Done        
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@d846d6c54be4:/#

**Comment by jielingit** [comment] 2019-06-07 18:09
I am getting the same issue. DNS look up does not work with gVisor and netstack in the Docker container. But without gVisor it works. 

> I am getting error in apt update inside the ubuntu image when I run it with gvisor, with runc it work fine. Can someone tell me how to fix it?
> content of the conf file inside the container:
> 
> root@d846d6c54be4:/# cat /etc/resolv.conf
> search utah.cloudlab.us
> nameserver 10.0.0.2
> nameserver 8.8.8.8
> 
> error:
> root@d846d6c54be4:/# apt update
> Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease
> Temporary failure resolving 'archive.ubuntu.com'
> Err:2 http://security.ubuntu.com/ubuntu bionic-security InRelease
> Temporary failure resolving 'security.ubuntu.com'
> Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
> Temporary failure resolving 'archive.ubuntu.com'
> Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
> Temporary failure resolving 'archive.ubuntu.com'
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> All packages are up to date.
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease Temporary failure resolving 'archive.ubuntu.com'
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease Temporary failure resolving 'archive.ubuntu.com'
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease Temporary failure resolving 'archive.ubuntu.com'
> W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease Temporary failure resolving 'security.ubuntu.com'
> W: Some index files failed to download. They have been ignored, or old ones used instead.
> root@d846d6c54be4:/#

**Comment by iangudger** [comment] 2019-06-07 19:22
I don't think that there is anything we can do to fix this on the gVisor side. Docker Compose seems to be assuming a shared loopback, which I don't think is conceptually compatible with network isolation. I think your only options are to not use network isolation (e.g. enable network passthrough in gVisor) or to fix, not use, or otherwise work around Docker Compose.

**Comment by jielingit** [comment] 2019-06-07 19:53
> I don't think that there is anything we can do to fix this on the gVisor side. Docker Compose seems to be assuming a shared loopback, which I don't think is conceptually compatible with network isolation. I think your only options are to not use network isolation (e.g. enable network passthrough in gVisor) or to fix, not use, or otherwise work around Docker Compose.

I am not using Docker Compose. Just Docker Run. It only has default `bridge` network.

```docker run --rm -dit --runtime runsc --name ubuntu_runs jie/ubuntu bash
a73e6e85de4cb6337c214f076f454fd5a5f415dc3ef7bd25951709a7a639b370

docker attach a73e6e85de4cb6337c214f076f454fd5a5f415dc3ef7bd25951709a7a639b370
root@a73e6e85de4c:/# cat /etc/resolv.conf 
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 10.21.0.2
search us-west-2.compute.internal
root@a73e6e85de4c:/# 
root@a73e6e85de4c:/# apt update
Err:1 http://archive.ubuntu.com/ubuntu bionic InRelease                  
  Temporary failure resolving 'archive.ubuntu.com'
Err:2 http://security.ubuntu.com/ubuntu bionic-security InRelease        
  Temporary failure resolving 'security.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists... Done        
Building dependency tree       
Reading state information... Done
5 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@a73e6e85de4c:/# 
root@a73e6e85de4c:/# nc -vz google.com
google.com: forward host lookup failed: Host name lookup failure : Resource temporarily unavailable
```

**Comment by iangudger** [comment] 2019-06-07 20:10
That looks like a different problem. Can you file a new issue and attach an strace log?

**Comment by jielingit** [comment] 2019-06-07 20:48
@iangudger Opened https://github.com/google/gvisor/issues/334

**Comment by nikosT** [comment] 2020-03-30 16:33
I confirm that DNS name is not working on docker-compose.

**Comment by D4rk4** [comment] 2020-05-20 11:44
Still not working with compose. Up!

**Comment by sloslo4** [comment] 2020-05-22 11:34
Same issue here

**Comment by dntq83** [comment] 2020-05-23 01:15
Same issue

**Comment by sloslo4** [comment] 2020-05-23 09:44
You shouldnt edit /etc/resolv.conf in container directly. Leave it 127.0.0.11
And try use this

    dns:
        - 8.8.8.8

in docker-compose.yml or *override.yml
----

**Comment by D4rk4** [comment] 2020-05-25 09:24
> You shouldnt edit /etc/resolv.conf in container directly. Leave it 127.0.0.11
> And try use this
> 
> ```
> dns:
>     - 8.8.8.8
> ```
> 
> ## in docker-compose.yml or *override.yml

It's not working for me...

**Comment by boostpaal** [comment] 2020-05-25 11:54
https://github.com/google/gvisor/issues/115#issuecomment-443700631

**Comment by sloslo4** [comment] 2020-05-25 12:18
> [#115 (comment)](https://github.com/google/gvisor/issues/115#issuecomment-443700631)

Its not right when inside container you have external **DNS**. When you put other address than "**127.0.0.11**" docker lose self intercommunication between hosts if you are in stack or something. 
Docker have own "**DNS proxy**" which connects from "**127.0.0.11**" to any external **DNS**. 

Don't put any change in containers resolv.conf. _It break functionality_. Edit your **DNS** by other method like **dns** settings in docker-compose.yml

**Comment by D4rk4** [comment] 2020-05-25 12:26
@sloslo4 you right, but anyway dns settings is ignored by docker-compose.

**Comment by romuloslv** [comment] 2020-06-18 01:48
Still not working, any predictions?

**Comment by amscanne** [comment] 2020-06-18 16:12
Hopefully someone on the project can look at Docker compose soon, but there's no timeline right now. The problem is fundamentally what Ian [notes above](https://github.com/google/gvisor/issues/115#issuecomment-443482476). The DNS server appears to be binding to localhost inside the container's network namespace. But the isolated container does not have direct access to the host network namespace unless network=host (passthrough mode) is enabled. For now the [workaround suggested above](https://github.com/google/gvisor/issues/115#issuecomment-443700631) seems reasonable, but I'm sure if there are any consequences wrt to service discovery, etc. (I don't know much about how Docker compose is using DNS and why it is doing what it is doing, which is why we need someone to dig in and understand that first.)

**Comment by romuloslv** [comment] 2020-06-19 16:47
@amscanne this [solution ](https://github.com/google/gvisor/issues/115#issuecomment-443700631 )is not working with: 

networks:
  lab:
    ipam:
      driver: default
      config:
        - subnet: 10.98.5.0/16

**Comment by ianlewis** [comment] 2020-09-08 23:14
I don't think this is an issue we can solve for good in gVisor as it has to do with how Docker binds to localhost for the DNS server. We can maybe document this better as it seems to be a fairly common issue.

**Closed** 2020-09-09 04:59 UTC
Labels: area: docker, area: docs, area: integration, area: networking

**Comment by ianlewis** [comment] 2020-09-09 05:14
I added a tutorial to the website that will be available at https://gvisor.dev/docs/tutorials/docker-compose/ so I'm going to close this issue. If there are further issues you have with DNS and docker compose feel free to open up another issue with the details.

**Comment by mindon** [comment] 2021-01-20 10:25
docker-compose using user defined networks no internal service names or host names resolved
- 127.0.0.11 names resolve not working (ping ok, nkloopup refused)
- /etc/hosts no host entry appended for depends_on services or links alias

docker-compose version 1.27.4, build 40524192

**Comment by ianlewis** [comment] 2021-01-20 23:32
@mindon This issue is closed. Could you open a new issue with a bit more details about how to reproduce your problem?

**Comment by mindon** [comment] 2021-01-21 07:24
> @mindon This issue is closed. Could you open a new issue with a bit more details about how to reproduce your problem?

my mistake, it should be a docker-compose issue

**Comment by phirestalker** [comment] 2022-11-25 18:55
Did anyone file a bug with docker-compose or docker about this? If, so would you provide a link to the issue?
